### ISSUE TITLE
Home offset

### ISSUE THREAD

**Issue by TheGamer497** [espidev/ProtectionStones#100]
I wanted to set offset_x and offset_y to 0.5, to make /ps home teleport player exacly on the center of the block, but when i change this in protection block file, there is an error, and the block is not loaded. Could you repair or add possibility to set home offset on example "0.5"?  (I am sorry if there are grammar mistakes or something like that in my report, I'm not from England and I can't speak english very well)

**Comment by espidev** [comment]
This will take a bit of work with conversions, but I will work on this. It seems it slipped my mind when I was making this.

**Comment by TheGamer497** [comment]
Okey, thanks for your help.

**Comment by espidev** [comment]
Fixed in 2.6.0
