### ISSUE TITLE
Recurring crash (Once a day) since i updated to 2.5.0

### ISSUE THREAD

**Issue by Leonardo-Fiori** [espidev/ProtectionStones#102]
Today i got this crash.. looks like an overload?
Never happened before. I recently updated PS to 2.5.0

[2019-10-16-1.log.txt](https://github.com/espidev/ProtectionStones/files/3733890/2019-10-16-1.log.txt)

Yesterday i got this:

[2019-10-15-1.log.txt](https://github.com/espidev/ProtectionStones/files/3733911/2019-10-15-1.log.txt)

After you have seen the logs please remove, it may contain some player's IPs.

Paper version 213, MC 1.14.4

**Comment by espidev** [comment]
Okay, the problem is I don't see any PS specific stuff in the crash.
What you can do is revert to your previous version, and see if the issue still occurs.
Another possibility is to ask around on the papermc discord, since they can probably read the crash report better than me.

**Comment by espidev** [comment]
is this still an issue?

**Comment by Leonardo-Fiori** [comment]
Nope. Plan was involved
