### ISSUE TITLE
/ps admin changeblock is not working

### ISSUE THREAD

**Issue by Leonardo-Fiori** [espidev/ProtectionStones#103]
Just tested! The /ps admin changeblock command simply does not work. With regular blocks and with heads. It does nothing. If i try it, it says  "The block to change to is not a registered protection block!"

I tested it on an old build of paper, paper 176. Now i will test it also on the latest one.

I used the alias of the PS block by the way. That is also the .toml file's name in my case.

Now I tried also on latest build.

If i do:

/ps admin changeblock world coal redstone

it says that the block to change is not a registered protection block.

coal.toml
https://pastebin.com/Vk488iwz

redstone.toml
https://pastebin.com/5LTbfUAY

"world" is my world's name

**Comment by espidev** [comment]
you have to use the material name  (ex. COAL_ORE)
I should make that more clear on the docs
