### ISSUE TITLE
Duping/Piston/A lot of dangerous bugs with Player Heads as PS!

### ISSUE THREAD

**Issue by Leonardo-Fiori** [espidev/ProtectionStones#104]
There are lots, lots of bugs with heads. It's so scary that i think i will stick with old regular blocks. They are safer.

Here is a small video, real shit happens. Heads can be pushed by pistons, they can be duped with /ps unhide... in the current state i strongly do not recomend to use heads as protection stones. Just stick to ores!

Usually they also suddenly stop being actual protection blocks, and when placed they don't do anything.

Protection Stones 2.5.0
Paper 223

https://youtu.be/YnOK4x6-4s8

**Comment by espidev** [comment]
Thank you for reporting.
I have been able to duplicate these bugs with 2.5.0, and so I am sorry I somehow missed such a large amount of testing when releasing the version...

I have rewritten the head code in 2.6.0, and the bugs have been fixed, but school has been really preventing me from having enough time to fully test so that I can release the version.

I really want to release the version this week, but it'll depend on if I have enough time

**Comment by espidev** [comment]
Should be fixed as of 2.6.0, reopen if there are more issues

**Comment by Leonardo-Fiori** [comment]
Testing again, this time more accurately. I found out a reaaally simple explit... just water and lava. Put a PS head in water, or make water flow on it. Same thing for lava. It will drop, and PS will be still there. You have to add some checks... i know, this is getting difficult. Just make sure to check everything related to destroying heads! :)

**Comment by espidev** [comment]
will be fixed in 2.6.1, forgot to disable block physics

**Comment by Leonardo-Fiori** [comment]
Tested again... man... player heads can be waterlogged. lol.
Try putting a bucket of water inside the same block of the player head.

**Comment by espidev** [comment]
I fixed the bug, but the texture appears to change when you waterlog it but it actually hasn't changed... going to have to investigate later

**Comment by espidev** [comment]
Should be fixed in 2.6.2...

**Comment by Leonardo-Fiori** [comment]
Player heads stopped working again in 2.6.2

Just try with PLAYER_HEAD:Notch

**Comment by espidev** [comment]
> Player heads stopped working again in 2.6.2
> 
> Just try with PLAYER_HEAD:Notch

Strange, because it works for me...

**Comment by espidev** [comment]
investigating

**Comment by espidev** [comment]
Okay I've identified some issues with non-base64 player heads. Doesn't seem to affect heads that use base64...

**Comment by espidev** [comment]
Fixed...
The item that was created by the plugin's nbt data where only the texture was applied, and not the player name data

**Comment by Leonardo-Fiori** [comment]
> Fixed...
> The item that was created by the plugin's nbt data where only the texture was applied, and not the player name data

Oh ok! :) this heads feature is a real pain in the as*! Hope that you have fixed it definetly! It's an hard work

I am testing it with base64 heads and infact it works, but the head, when waterlogged, loses it's textures. When i relog in the server the texture loads correctly.

**Comment by espidev** [comment]
> I am testing it with base64 heads and infact it works, but the head, when waterlogged, loses it's textures. When i relog in the server the texture loads correctly.

Yeah I noticed that, I think it's just a client thing because I tried replacing the block but the texture just won't come back without a relog.

The actual block server-side is correct though.

**Comment by espidev** [comment]
eta for 2.6.4 release: maybe a week, I want to group it up with a few other bug fixes
