### ISSUE TITLE
Default flags only to nonmembers

### ISSUE THREAD

**Issue by erDUKE21** [espidev/ProtectionStones#107]
How to set in the config file the flags to work only on nonmembers, i mean, in the block1.toml file i want to set the flag "block-break deny" only to nonmembers by default. Is that possible?

**Comment by espidev** [comment]
Yes, add -g nonmembers after the flag (block-break deny -g nonmembers)

**Comment by erDUKE21** [comment]
Thank you very much, but i added that before and it works, is that ok? (-g nonmembers block-break deny)

**Comment by espidev** [comment]
Actually that's the correct way, ignore what I said above

**Comment by erDUKE21** [comment]
Ok man, thank you very much
