### ISSUE TITLE
Forcemerge is quite inefficent

### ISSUE THREAD

**Issue by Leonardo-Fiori** [espidev/ProtectionStones#108]
Look at these results:
https://imgur.com/a/NZwkFTR

For not efficient i don't mean performance inefficiency. I mean that it actually do not find a lot of regions to merge.

I have hundreds of PS regions on my server, i downloaded an offline copy of it and finally tried the /ps admin forcemerge functionality... as you can see in the imgur album many regions did not merge.

Why? Can this be improved?

**Comment by espidev** [comment]
What was the output, did any regions get merged? Possibly my requirements for merging are too strict, the flags, the owners, the members all have to be the same

**Comment by Leonardo-Fiori** [comment]
Yeah i got a regular output... i don't think it is an actual bug. It's just how it is intended to work. Requirements for merging are too strict... you should probably just check owners, at least one owner in common between the two areas. If you want you could make this configurable...

merge:
  matching_all_owners_required: false
  at_least_one_owner_required: true
  matching_members_required:  false
  matching_flags_required:  false
  ...

**Comment by espidev** [comment]
do /ps admin forcemerge world no_member_match no_flag_match one_owner_match
