### ISSUE TITLE
Permission System

### ISSUE THREAD

**Issue by espidev** [espidev/ProtectionStones#110]
Moved from #109 

Add a permission system that replaces WorldGuard's "owner" and "member" system, which will allow creating new roles and adding specific permissions to each. Each role will also have to be classified as an "owner" inherit or "member" inherited group, in order for flags to apply properly. The actual permissions that can be given would be:
* Change home
* Change flags
* Destroy PS
* and more

There is also a "renter" role created by default for renters

**Comment by Leonardo-Fiori** [comment]
prevent members from changing flags was not possible in any other ways other than rewriting the entire WG permission system?

**Comment by espidev** [comment]
I think I was a bit ambitious with this, I'm probably going to start by adding an option for renters to be either member or owner

**Comment by Leonardo-Fiori** [comment]
How is it proceding @espidev ?

**Comment by espidev** [comment]
I've been busy with school stuff, so development has been slow

**Comment by espidev** [comment]
Far too complicated, for now will just focus on what was originally proposed in #109
