### ISSUE TITLE
Players can buy unlimited protected zones

### ISSUE THREAD

**Issue by HgeX** [espidev/ProtectionStones#113]
At the moment, /ps buy ignores how much zone do players have. This causes issues, since they can bypass the limit easily by buying as many zones as they want, even though the maximum number is set by the ps limit permission.

**Comment by espidev** [comment]
Will be grouped up in 2.6.4

**Comment by HgeX** [comment]
Awesome, thx! :D

**Comment by espidev** [comment]
Fixed in 2.6.3
