### ISSUE TITLE
Some problems with renting

### ISSUE THREAD

**Issue by HgeX** [espidev/ProtectionStones#114]
The new renting feature is awesome, I really like it. However, it has a couple of flaws that makes it unusable in it's current stage.

> Here are my suggestions that would make this funtcion better in my opinion:

- Create permission limit for renting (maybe `protectionstones.rent.limit.<number>` ?), so players wouldn't have access to unlimited zones by renting.

- Add config options to determine the minimum and maximum cost and time. For example: `max-rent-price`, `min-rent-price`, `max-rent-time` and `min-rent-time`. This would prevent players from setting too high prices.

- **MAYBE** Make /ps info display for how long is the current owner renting the zone.

**Comment by espidev** [comment]
Eta maybe a week

**Comment by espidev** [comment]
Delayed until I have time...

**Comment by espidev** [comment]
Will add permission in time for 2.6.3

**Comment by espidev** [comment]
The options will be in 2.6.4

**Comment by espidev** [comment]
Busy this week, might have time on the weekend but lots of school projects due

**Comment by HgeX** [comment]
Okay, do it when you have time! I can wait! :D

**Comment by espidev** [comment]
Should be finished for 2.6.4
