### ISSUE TITLE
Heads used for protection stones lose their data after hiding and unhiding

### ISSUE THREAD

**Issue by HgeX** [espidev/ProtectionStones#115]
The problem is the same when using ps admin changeblock command.

- As you can see, I was able to place the protection block without any problems.
![place](https://user-images.githubusercontent.com/41118733/68993996-eee2da00-087d-11ea-93f3-ebc9ebc58c45.png)

- Hiding it worked just fine.
![hide](https://user-images.githubusercontent.com/41118733/68993997-eee2da00-087d-11ea-8047-92bae6da8376.png)

- Unhiding wasn't so successful though. :(
![unhide](https://user-images.githubusercontent.com/41118733/68993998-eee2da00-087d-11ea-8b82-cdf0e40256c5.png)

**Comment by espidev** [comment]
This was supposed to have been fixed in 2.6.0...

If you relog, does the texture appear?
Are mobs disabled on your server?

**Comment by HgeX** [comment]
The texture doesn't appear after relogging, and mobs aren't disabled on the server.

**Comment by espidev** [comment]
What's the head texture you are using? Base64 or player name

**Comment by HgeX** [comment]
```
type = "PLAYER_HEAD:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjNkNWU0M2RlNWQ0MTc3YzRiYWYyZjQ0MTYxNTU0NDczYTNiMGJlNTQzMDk5OGI1ZmNkODI2YWY5NDNhZmUzIn19fQ=="
# Another way to refer to the protection stone
# Can be used for /ps give and /ps get
# Must be one word (no spaces)
alias = "teszt"```

**Comment by espidev** [comment]
Strange I just tested and it works, are you using an offline server?

**Comment by HgeX** [comment]
Yes, it's offline.

**Comment by espidev** [comment]
Okay I'm unable to duplicate this bug

**Comment by espidev** [comment]
Could you try using PLAYER_HEAD:player-name and seeing if that works? I just want to see if it's the command that doesn't work

**Comment by HgeX** [comment]
Okay, I'll do that today!

**Comment by HgeX** [comment]
I've tested it, and it's weird. If I use player names then the plugin doesn't even create a protection. With base64 it works till I run the hide/unhide commands.

**Comment by espidev** [comment]
I'm going to release 2.6.3 later this week with a few fixes...

It should fix the player name issue and has a possible fix for the unhide issue you are having, but I'm still not able to duplicate your bug so we'll see

**Comment by HgeX** [comment]
Okay, thank you so much! :)

**Comment by espidev** [comment]
Could you try again with 2.6.3?

**Comment by HgeX** [comment]
Hey! Sorry for the delay, I was busy last week. :( It works flawlessly, thank you! :D

**Comment by espidev** [comment]
Awesome
