### ISSUE TITLE
Taxes for Regions

### ISSUE THREAD

**Issue by Leonardo-Fiori** [espidev/ProtectionStones#119]
Could you rapidly sneak this feature in the next release please? My server is having huge problems with economy inflation. I need to tax players quickly, before economy is 100% dead. Some own a very large amount of emeralds.. way too much. I can find ways to make them spend, but i also need taxes... and what's better than taxing land property? lol

inside each protectionstone .toml file add:

tax-price: X money
tax-every: X in-real-life days
unpaid-taxes: unclaim/disown

And add a configurable message that is sent every time the user logs in the server! and every X seconds.

Example: "You have {time-left} days left to pay taxes {amount}$ for claim at {region-coords}"

**Comment by espidev** [comment]
I will try to see if I can group it up in 2.6.4

**Comment by espidev** [comment]
Do you have to explicitly pay taxes? Or would it be automatic

**Comment by Leonardo-Fiori** [comment]
/ps taxes pay "regionname"
/ps taxes autopay (toggles autopay on and off)

**Comment by Leonardo-Fiori** [comment]
A good levelling measure could be also a permission like:

ps.taxes.multiplier.0 (no taxes)
ps.taxes.multiplier.1 (regular taxes)
ps.taxes.multiplier.2 (2x taxes)

But that's something more advanced you could implement later on

**Comment by espidev** [comment]
Okay, I'll have to see if I have time this week, soo many assignments due

**Comment by espidev** [comment]
Okay see my issue is what to do when there are multiple owners. Do they all get removed if they are unable to pay taxes?

**Comment by Leonardo-Fiori** [comment]
@espidev they should all get notified... if no one paid, they are all debtors and shall be punished with the removal! :)

**Comment by espidev** [comment]
Yeah this feature will take a while to implement, been trying to do it for 2 weeks

**Comment by espidev** [comment]
Should owners automatically start autopaying taxes (will require a region upgrade)

**Comment by espidev** [comment]
The performance for taxes isn't going to be spectacular because it has to scan through every single region often...

**Comment by Leonardo-Fiori** [comment]
> Should owners automatically start autopaying taxes (will require a region upgrade)

Could you explain further? i did not get that :)



> The performance for taxes isn't going to be spectacular because it has to scan through every single region often...

Oh, why? Don't each user have his own list of owned regions? You need to scan the whole list?

**Comment by espidev** [comment]
Meaning that should existing regions be upgraded so that someone is set to auto-pay

**Comment by espidev** [comment]
Okay so I need to release a bunch of bug fixes in 2.6.4, so it will also have the renting feature half-complete...

TODO:
* tax message on join
* /ps tax info, with clickable text to /ps tax info [region]
* upgrade regions to have an owner set to autopay
* set a punishment rather than just deleting regions

**Comment by Leonardo-Fiori** [comment]
> Meaning that should existing regions be upgraded so that someone is set to auto-pay

Oh yeah, i think taxes should be automatically set to autopay for existing regions.



> Okay so I need to release a bunch of bug fixes in 2.6.4, so it will also have the renting feature half-complete...
> 
> TODO:
> 
> * tax message on join
> * /ps tax info, with clickable text to /ps tax info [region]
> * upgrade regions to have an owner set to autopay
> * set a punishment rather than just deleting regions
> * figure out a way to deal with rented regions

Good work man!

**Comment by espidev** [comment]
I'm not expecting the full version (2.7.0) to be released this week or next week because of exams unfortunately...

I'll see what I can do, but there is still a lot of work left

**Comment by espidev** [comment]
Okay, exams are over, I can start to look at this again...

Time to start tackling the long requested features list lol

**Comment by espidev** [comment]
What is left to be done:
* Date formatting for tax periods, payment periods, and so on for merged regions
* Possibly a command to pay for all taxes due

**Comment by espidev** [comment]
Done for now, will be in 2.7.0, if you wanted to try it there are devbuilds on https://ci.espi.dev/job/ProtectionStones/
