### ISSUE TITLE
error after changing the price to 10000 in block file

### ISSUE THREAD

**Issue by k1lbu** [espidev/ProtectionStones#123]
it says error in console and asks if its up to date ?

**Comment by espidev** [comment]
Please give me the actual error

**Comment by espidev** [comment]
I suspect you might need to add a .0 (ex. 10000.0)

**Comment by k1lbu** [comment]
Hey dude i cant add more blocks it gives errors... but if i wanna sell the
emerald protection block in a chest shop then what id do i give it ? the
emerald didnt work i  tried...
thanks for response btw!
oh and if u have more time to then read this :
i recently started searching for a plugin that takes money when you use
/home
but i cant find any so can you maybe help me out with that?
BLESS YOU !!!
THANK YOU !!!

Kontakt EspiDev (<notifications@github.com>) kirjutas kuupäeval E, 23.
detsember 2019 kell 00:07:

**Comment by espidev** [comment]
@k1lbu again, you have to paste the error here so I know what's wrong. I've never tested with chestshop, but I know the shopchest plugin and  command signs plugins work well with protectionstones. In essentials, you can set a teleportation charge.

**Comment by espidev** [comment]
no response
