### ISSUE TITLE
protectionstones.adjacent.-1 does not work, used 999999 instead

### ISSUE THREAD

**Issue by Leonardo-Fiori** [espidev/ProtectionStones#125]
I recently enabled the adjacent limit functionality, and (aside players blaming bla bla) i noticed that the bypass (-1) does not work. I used protectionstones.adjacent.999999 instead to bypass the non adjacent limit for some users.

> 

Sets the number of non-adjacent regions players can have if "regions_must_be_adjacent" is true. Unlimited with -1.
--

**Comment by espidev** [comment]
Will be fixed in 2.6.4, turns out I just forgot to add the functionality
