### ISSUE TITLE
Make -e flag in config more user friendly

### ISSUE THREAD

**Issue by Ant4rez** [espidev/ProtectionStones#128]
**Issue:**
In the last update (2.6.4) the regions created with the blocks now supports this worldguard flag:

"Added -e (empty flag) support for flags in config, allowing for disabling block break warning messages"

So in my blocks file i added the following line: "deny-message -e",
the problem is now if a player try to open a chest for example, in another player region where he is not a member or owner, where he is a stanger. He literaly see the message "-e" and not an empty message or no message.

**Server Version:** Paper version git-Paper-239 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
**Worldguard Version:** WorldGuard 7.0.2 Bukkit-Official (7.0.2-SNAPSHOT;bf2593e)
**Worldedit Version:** Bukkit-Official (7.0.1;61bc012)
**Vault Version:** 1.7.2-b107
**Luckperms Version:** 5.0.39
**ProtectionStones:** 2.6.4

**Blocks:** [blocks.zip](https://github.com/espidev/ProtectionStones/files/4054885/blocks.zip)

![2020-01-13_14 57 22](https://user-images.githubusercontent.com/25251234/72279523-13a4c500-3615-11ea-9848-7e7b4f343b13.png)

**Comment by espidev** [comment]
I believe you have to add -e before the flag name, not after (-e deny-message)
I've realized the way I implemented this is pretty dumb, so I'll try to figure out a less specific way to implement the flag.

**Comment by Ant4rez** [comment]
> I believe you have to add -e before the flag name, not after (-e deny-message)
> I've realized the way I implemented this is pretty dumb, so I'll try to figure out a less specific way to implement the flag.

That's weird because always that i made a region with worldguard, like protect the spawn i use the command "rg flag <name> denny-message -e" and doing that works fine. So i inferred that for the regions flags it was the same way lol.

**Comment by Ant4rez** [comment]
By the way, this happen if i try to use "-e deny-message" https://paste.ubuntu.com/p/Vm3wpkcqQK/

**Comment by espidev** [comment]
Okay, that's weird, I thought I tested it
I'll have to investigate when I have a bit of time this week, and quickly release 2.6.5

**Comment by Ant4rez** [comment]
You can test it with the blocks that i attached befores, just change or add the "-e denny-message" flag in the files, so you can test with the same files dat i use. btw i know u are bussy, but i will report everything dat i will found that doesn't works fine, so you can fix it latter when you can and made a better plugin=D.

**Comment by espidev** [comment]
Okay I have to delay 2.6.5 until after my exams...

**Comment by espidev** [comment]
Should be fixed for 2.6.5, reopen if you have issues on that version.
