### ISSUE TITLE
ps add showing vanished players

### ISSUE THREAD

**Issue by AguaDeLaMiseria** [espidev/ProtectionStones#129]
As title says. May be considered something minor, but it would be nice for the predictive commands to not show vanished players, or if there is a solution for this, please let me know.

**Comment by espidev** [comment]
Hopefully will make it into 2.6.5, though I have exams coming up so it'll have to come after that

**Comment by espidev** [comment]
Since I can't check every single visibility plugin, I'm just checking if the player can actually see (like literally has invisible effect). 
This is in 2.6.5, please reopen if you encounter issues
