### ISSUE TITLE
Auto Hide placing Error.

### ISSUE THREAD

**Issue by gwladyka** [espidev/ProtectionStones#130]
Error on placing protection block, when "auto_hide = true".
https://pastebin.com/fZM0NAK5

**Comment by espidev** [comment]
i'm unable to look at this for a week because I have exams

**Comment by espidev** [comment]
Figured out the bug, seems to only apply to skulls.
Will be fixed in 2.6.5

**Comment by espidev** [comment]
Please reopen if you still have issues when 2.6.5 comes out.
