### ISSUE TITLE
Enhancement: Allowed Flags Custom

### ISSUE THREAD

**Issue by AguaDeLaMiseria** [espidev/ProtectionStones#132]
Even though you can specify groups for the default flags of a block (-g members whateverflag deny); I don't think there is a way for the allowed flags (the ones that can be set/edited by region owners) to specify or deny the edition of certain groups. Let me explain this with an example: you can allow the pvp flag to be edited, and you can set it to be allowed or denied, for all, members, nonowners, etc. I think it'd be a great feature so you can for example only allow or deny pvp for all, without the ability to change the group the rule applies for. So in allowed_flags for block1.toml lets say, we could do something like ["pvp" -g all, "interact"  -g all,members].

I bring this here, mostly because you can with the pvp flag, make you invulnerable and yet kill other people if you set the group to members (or nomembers, don't recall) and I'd like my players to take the risk of being killed if they allow pvp (in a survival enviroment), and I can also think of other situations when people may find this feature possible. Hope you can add this, great plugin!

**Comment by espidev** [comment]
Just to clarify, you want to whitelist groups for flags?

I'll have to think about how to do this

**Comment by AguaDeLaMiseria** [comment]
Yeah, that would be another way to look at it. I'd like to be able to only allow or deny a flag for, lets say, all, or members. Not for all, members, nonmembers, owners, nowoners, and so.

**Comment by espidev** [comment]
Being worked on

**Comment by espidev** [comment]
Added to 2.6.7

**Comment by espidev** [comment]
The syntax is "-g all,members pvp" for consistency
