### ISSUE TITLE
TP after removing Merged Region

### ISSUE THREAD

**Issue by banit** [espidev/ProtectionStones#134]
Tp to a Region wich was merged before is not possible. 

- Player places PS1 and PS2 and merges them.
- Player Names that Region to Test.
- Player can tp to region Test.
- PS1 gets removed either by Admin or Player.
- /ps tp test does not work anymore.
- /ps list still shows the same region name.
- its not possible to find the remaining ps with a command.

this even breaks the tp via chat from ps list

Server Version Paper 1.15.2 - 77
PS 2.6.5

**Comment by espidev** [comment]
Do you know if this works after a server restart? I'm suspecting that I didn't reload the name cache

**Comment by espidev** [comment]
Never mind, found the bug. Will be in 2.6.6

**Comment by banit** [comment]
Bug still exists.. :D 
https://i.vgy.me/bs9Oxi.png
after restart it will tp you but on the wrong PS

**Comment by espidev** [comment]
Does the bug exist after a server restart?

**Comment by banit** [comment]
yes. behaviour changes. before restart it cant find the region. after restart it will find the region but will tp you to the first PS instead of the second

**Comment by espidev** [comment]
Are there two regions after the unmerge? It can only give the name to one of them.

**Comment by espidev** [comment]
Oh I realized, I'm not updating the /ps home location.

Problem about that is that I have to keep that location when unmerging, because some people may have set a custom spot for their /ps home, so I can't change that functionality.

And you said before the restart it can't find the region. That's strange, I thought I had just fixed that... Just to confirm, when you do /ps admin version it says 2.6.6 right?

**Comment by banit** [comment]
yes 
https://i.vgy.me/q01bp3.png

**Comment by banit** [comment]
i couldnt find a unmerge command.. maybe add one so i can unmerge the regions beforehand and then remove those ps one by one.

**Comment by espidev** [comment]
An unmerge command isn't exactly very intuitive for people to use, it's definitely easier to break the block. How many regions are merged together after the unmerge? Is it just one, or is it still a few regions?

I'm just trying to find where in my code this would be happening

**Comment by banit** [comment]
well ive only tested it with two stones. we are starting to implement ps on one of our servers and were testing the behaviour beforehand. we would like to be able to find all the stones a user places so we can remove them. what i didnt try was searching for the id instead of the name.. so its probaly a mistake on our side. but it still would be conveniant to tp to a named region. 

another idea would be a command to cycle through all of a users protection stones...  and/or the ability to tp when clicking on a protection stone when you use /ps list name

**Comment by espidev** [comment]
Okay, I did find the same issue with 3+ stones (somehow I forgot that).

You can actually use /ps region remove [player] to do that.

**Comment by espidev** [comment]
I've just looked through /ps region remove code (it was from before I forked the plugin), and I noticed that any region with that player as an owner would be removed. I changed it for 2.6.7 so that the region is only removed if there are no other players.
