### ISSUE TITLE
Sponge Support

### ISSUE THREAD

**Issue by ivandelp** [espidev/ProtectionStones#140]
Hello :)

I would like if it is possible and you have time that is also the plugin available in Sponge, there are few protection plugins and many users who will choose this for their Sponge Servers.

**Comment by espidev** [comment]
It'd be a lot of work...

So no for now, since I'd have to either fork the project or abstract out the API which would take quite a bit of time. If other people were interested in attempting to do this at the moment, let me know.

I'll leave this open though.

**Comment by Seshpenguin** [comment]
@espidev How much work is involved
I might be interested in trying.

**Comment by espidev** [comment]
Well the first issue is that WorldGuard is not ported to sponge yet...
WorldEdit is though, and they've abstracted out the Bukkit specific WorldGuard parts

**Comment by Seshpenguin** [comment]
> Well the first issue is that WorldGuard is not ported to sponge yet...
> WorldEdit is though, and they've abstracted out the Bukkit specific WorldGuard parts

I'll take a look into it

**Comment by espidev** [comment]
Going to close this for now since WorldGuard would have to be ported
