### ISSUE TITLE
Home other world

### ISSUE THREAD

**Issue by artukros2** [espidev/ProtectionStones#141]
Hello,
The problem is that when I am in the world "1" and the protection stone is set in the world "2", after entering "/ ps home" in the world "1" it does not show me houses from the world "2". How can you fix it.

**Comment by espidev** [comment]
Because of historical reasons, ProtectionStones has not really been cross-world, since there can be the same region IDs in different worlds.

You have to set a /ps name on a region for it to show up on all worlds, since names are unique.

**Comment by artukros2** [comment]
> You have to set a /ps name on a region for it to show up on all worlds, since names are unique.

This option does not work. / ps home does not show even named ps in another world.

**Comment by espidev** [comment]
I looked through the code and I realized I'm dumb, I have not implemented this yet.

Will probably make it's way for 2.6.9

**Comment by artukros2** [comment]
As you will write, you can add that after entering / ps home (X Y Z) (world) is displayed so that you can teleport from every world :D.

**Comment by espidev** [comment]
Yeah I can hopefully get this released within a week

**Comment by espidev** [comment]
In 2.6.9, fixed name behaviour

Not going to do the world argument at the moment, because of the confusion with tab complete
