### ISSUE TITLE
claim flag group kick

### ISSUE THREAD

**Issue by PackCraft** [espidev/ProtectionStones#142]
Since 1.15.2, on change the claim flags group for "greeting-title" and "farewell-title" we are making kick for "illegal characters in chat "
![image](https://user-images.githubusercontent.com/35098809/74607198-fe6cfb80-50d6-11ea-8485-ca5f4c77f021.png)

**Comment by espidev** [comment]
Flag groups I don't believe actually exist for greeting and farewell, I'll have to double check that

**Comment by espidev** [comment]
Never mind, they do, I'll need to do further investigation

**Comment by PackCraft** [comment]
Thanks

**Comment by espidev** [comment]
Fixed, will be in 2.6.9
