### ISSUE TITLE
Limited number of placed regions.

### ISSUE THREAD

**Issue by OlekMK342** [espidev/ProtectionStones#145]
Hi, it's me again ._.
I was looking for how to do something like "limited amount of bets for a given region" I don't know if it is possible to do it on this version of the plugin (1.15.2). On the older version, you could probably do something like this using permissions and plugin configuration.

I have a question, can this be done on this version?
If can, I would like to ask you how to do it.
If not, I suggest adding something like this if you can, if you could, it would be helpful, you could add permissions to specific ranks just like on the old version of the plugin.

**Comment by espidev** [comment]
Could you explain what you mean by "bets"? Are you talking about a limit to the number of regions you can have? That can be done by giving the permission "protectionstones.limit.x" or "protectionstones.limit.alias.x" were alias is the one specified in the config for the block.

You can view the permissions here: https://github.com/espidev/ProtectionStones/wiki/Permissions

**Comment by OlekMK342** [comment]
Sorry, I still use google translate : /

If I add permissions, just for example: "protectionstones.limit.3", will it cause that every bloack can be wagered 3 times?
"protectionstones.limit.alias.x" What is it?

I apologize for having stupid and lacking English skills.

**Comment by espidev** [comment]
protectionstones.limit.3 will allow a player 3 protection stone regions max.

Check the block config for 
```
alias = ...
```
protectionstones.limit.alias.3 <- put alias here
This will allow a player 3 protection stone regions of type "alias" max

**Comment by OlekMK342** [comment]
ok works, thanks for help that's all what i need.
:)
