### ISSUE TITLE
Use PROTECTION_STONES:alias as ingredient in crafting

### ISSUE THREAD

**Issue by kazik56** [espidev/ProtectionStones#146]
I'm requesting a new feature as discussed extensively on Discord #discussion channel by CarpetCaptain discord user. 

The idea: Be able to use crafted protection stones (or other items) as one of crafting ingredient for crafting another protection stone. 

Protection stones are usually blocks (like Obsidian block), often crafted in original way on our server, so option to prevent people from obtaining it 'the normal way' is required to circumvent the possibility of crafting protection stone with using normal item and not the protection stone as ingredient itself.

I think I wrote big enough explanation of this idea on Discord channel so I won't really write any examples there.

**Comment by espidev** [comment]
Will be worked on when I have time

**Comment by espidev** [comment]
If you wanted it early, you can get it here: https://ci.espi.dev/job/ProtectionStones/239/artifact/target/protectionstones-2.6.9.jar

Otherwise, this will be grouped up in 2.7.0
