### ISSUE TITLE
Renting an offline player ps

### ISSUE THREAD

**Issue by AguaDeLaMiseria** [espidev/ProtectionStones#147]
As title says, it kinda works when a player, for example, rents your ps when you are offline, but it will throw this error: https://pastebin.com/vLDQ940V 

Can't confirm if it occurs everytime the rent makes the payment, but it does when you issue the command for the first time. I'll come here if I can provide more details

**Comment by AguaDeLaMiseria** [comment]
Yeah, it won't take out the money when the renting starts the period again if the tenant is offline.

**Comment by espidev** [comment]
will try to fix asap

**Comment by espidev** [comment]
This will be in the 2.6.10 patch release
