### ISSUE TITLE
ps give command error.

### ISSUE THREAD

**Issue by SliderKP** [espidev/ProtectionStones#152]
when i try to give a player a PS with the command ps give in BossShopPro i get the message of PS "you have no permission to give block"

but if i use the  command any other way, works perfect... can you tell me why this happens ?

**Comment by espidev** [comment]
I'm guessing that the plugin is running the command as the user. /ps give should not be allowed for normal users to run, the command needs to be run from the console.

**Comment by SliderKP** [comment]
but the plugin BossShopPro execute the command by console, not by user, all my items in BossShopPro are sended with the command "/give" for example and works fine

**Comment by espidev** [comment]
Have you tried running the exact same command from the console manually? There may be something wrong with the way you have configured the shop

**Comment by espidev** [comment]
no response

**Comment by SliderKP** [comment]
> Have you tried running the exact same command from the console manually? There may be something wrong with the way you have configured the shop

in console works fine, but in boss shop pro, nope.

**Comment by espidev** [comment]
did you use "playercommand" or "command" as the RewardType, it has to be "command" because that would run from the console

https://www.spigotmc.org/wiki/bossshoppro-rewardtypes/
