### ISSUE TITLE
'/ps get' shows incorrect sizes

### ISSUE THREAD

**Issue by Dragoboss** [espidev/ProtectionStones#157]
Hey Espi, it's been a while.

Been looking at the plugin the last few days and started to use it again in one of my servers.
What I noticed right away is that '/ps get' shows incorrect sizes:

If you set the **Radius** of a ProtectionStone to 15 by 15 (by 15), '/ps get' will say the size is 15x15.
But in reality:
If I place my PStone on Coordinates 0, 0, it protects an area of 31x31 blocks.
In fact per definition the size is always _(2 * r) + 1_ because the position of the PStone itself is also protected. So you will **always** end up with an uneven amount.
If I put my PStone to X-radius 10, Z-radius 10, it will be _(2 * 10) + 1_ --> _20 + 1_ --> _21_ so total _21x21_ protected area.

To illustrate this, here's the following image:
![image](https://user-images.githubusercontent.com/455989/78606071-fcb0f000-785c-11ea-97ea-b0f9b4dc2574.png)

It is not a big issue so low priority, but just wanted to let you know.
Kind regards,

- Drago

**Comment by espidev** [comment]
Wow, somehow I did not notice that.

Will be fixed in v2.7.2, though I think I will actually just add a description field to the config instead of showing the size

**Comment by espidev** [comment]
Will need a manual change or reset of messages.yml for the get.gui_block field in order to show the description instead of the radius
