### ISSUE TITLE
Command Issue

### ISSUE THREAD

**Issue by ivandelp** [espidev/ProtectionStones#158]
When I do /ps removeowner (user) appeared an error in console.

https://pastebin.com/0e3TVQki

Seems if you have all perms appeared the error.

And as a player, I can't be deleted.

**Comment by espidev** [comment]
Will be fixed in v2.7.2 ASAP

**Comment by espidev** [comment]
Wait, looking at this error I am very confused... Are you running the latest version? Also, is there a message in chat when it occurs?

**Comment by ivandelp** [comment]
Last version, I leave and joined on the server and solver at the moment

**Comment by espidev** [comment]
solved meaning it fixed itself?

**Comment by ivandelp** [comment]
At the moment yes

**Comment by espidev** [comment]
When did this occur? Was it when you first joined the server?

**Comment by ivandelp** [comment]
I am added to a protection as owner and then I want to remove me to that protection.

Before I enable taxes / rent in config and I do /ps reload

**Comment by espidev** [comment]
oH found the issue

**Comment by ivandelp** [comment]
Yes?

**Comment by espidev** [comment]
It will be fixed in 2.7.2, it was a very specific issue in the code

**Comment by ivandelp** [comment]
I'm glad you found it :)
