### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by 007Gh7** [espidev/ProtectionStones#167]
Hello. I have the following problem after translating the messages plugin file has stopped working and it is 100% well translated. My question is this, can anything be done about it?

**Comment by espidev** [comment]
Please double check for any errors in the console, and send them here.

**Comment by 007Gh7** [comment]
Could not load 'plugins\ProtectionStones-2.7.3.jar' in folder 'plugins'

Something I broke and nwm what :( now something like this is displayed and this is the only message I get and I just wanted to translate from English to Polish :(. Can I find out why I can't load the file into the plugins folder?

**Comment by espidev** [comment]
Uhhh that is not the full error...

Do you have worldguard and worldedit, and are using spigot or paper?

**Comment by 007Gh7** [comment]
Yes, I have WorldGuard. But it's a slightly different worldguard because it's in gui, not like the basic one

**Comment by espidev** [comment]
uhh what, where did you get it from

**Comment by espidev** [comment]
also there has to be the full error in the console, do you actually have access to it?

**Comment by 007Gh7** [comment]
https://www.spigotmc.org/resources/ultra-regions.58317/ this is it

**Comment by espidev** [comment]
okay but that's not worldguard
you must have worldguard

**Comment by 007Gh7** [comment]
ah okey

**Comment by 007Gh7** [comment]
There is one thing that works, but English to Polish translation does not currently work. When I add a changed language, the server automatically changes the language to the basic one, which is English.

**Comment by espidev** [comment]
how so, is the messages.yml reset? are there errors in the console?

**Comment by 007Gh7** [comment]
yes messages.yml resets itself :(

[ProtectionStones] Enabling ProtectionStones v2.7.3
[21:45:59] [Server thread/INFO]: [WorldGuard] Registering session handler dev.espi.protectionstones.flags.GreetingFlagHandler
[21:45:59] [Server thread/INFO]: [WorldGuard] Registering session handler dev.espi.protectionstones.flags.FarewellFlagHandler
[21:45:59] [Server thread/INFO]: [ProtectionStones] PlaceholderAPI support enabled!
[21:45:59] [Server thread/WARN]: [ProtectionStones] Loaded class org.apache.commons.io.IOUtils from CraftserveAgent v20200313-1954 which is not a depend, softdepend or loadbefore of this plugin.
[21:45:59] [Server thread/INFO]: [ProtectionStones] Protection Stone Blocks:
[21:45:59] [Server thread/INFO]: [ProtectionStones] - EMERALD_ORE (64)
[21:45:59] [Server thread/INFO]: [ProtectionStones] Building region cache...
[21:45:59] [Server thread/INFO]: [ProtectionStones] Building UUID cache... (if slow change async-load-uuid-cache in the config to true)
[21:45:59] [Server thread/INFO]: [ProtectionStones] Checking if PS regions have been updated to UUIDs...
[21:45:59] [Server thread/INFO]: [ProtectionStones] žfProtectionStones has successfully started!

**Comment by espidev** [comment]
Looks fine, is that from loading it with the messages.yml?

**Comment by 007Gh7** [comment]
yes

**Comment by espidev** [comment]
try loading it in with /ps reload

**Comment by 007Gh7** [comment]
[21:49:59] [Server thread/INFO]: Reloading config...
[21:49:59] [Server thread/INFO]: [ProtectionStones] Protection Stone Blocks:
[21:49:59] [Server thread/INFO]: [ProtectionStones] - EMERALD_ORE (64)
[21:49:59] [Server thread/ERROR]: Cannot load plugins\ProtectionStones\messages.yml
org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'string', line 219, column 3:
      help: '&b> &7/ps region [list|re ...
      ^
expected <block end>, but found '<scalar>'
 in 'string', line 222, column 53:
     ... racza &b%player%&7: &b%regions%'.
                                         ^

        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) ~[paperspigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[paperspigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[paperspigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:183) [paperspigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
        at dev.espi.protectionstones.PSL.loadConfig(PSL.java:399) [ProtectionStones-2.7.3.jar:?]
        at dev.espi.protectionstones.ProtectionStones.loadConfig(ProtectionStones.java:408) [ProtectionStones-2.7.3.jar:?]
        at dev.espi.protectionstones.commands.ArgReload.executeArgument(ArgReload.java:58) [ProtectionStones-2.7.3.jar:?]
        at dev.espi.protectionstones.PSCommand.execute(PSCommand.java:127) [ProtectionStones-2.7.3.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) [paperspigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:723) [paperspigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:708) [paperspigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
        at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:443) [paperspigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:407) [paperspigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [paperspigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [paperspigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'string', line 219, column 3:
      help: '&b> &7/ps region [list|re ...
      ^
expected <block end>, but found '<scalar>'
 in 'string', line 222, column 53:
     ... racza &b%player%&7: &b%regions%'.
                                         ^

        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:572) ~[paperspigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[paperspigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[paperspigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:217) ~[paperspigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[paperspigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:239) ~[paperspigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:230) ~[paperspigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:218) ~[paperspigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[paperspigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85) ~[paperspigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108) ~[paperspigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:141) ~[paperspigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:525) ~[paperspigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:438) ~[paperspigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) ~[paperspigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
        ... 15 more
[21:49:59] [Server thread/INFO]: Completed config reload!
[21:50:03] [User Authenticator #2/INFO]: UUID of player Gh05tt77 is 0bf0b91f-5ec0-4d54-8614-8da0534a159e
[21:50:05] [Server thread/INFO]: [ReflectionHelper] I am loaded from package org.inventivetalent.glow.reflection.minecraft
[21:50:05] [Server thread/INFO]: [ReflectionHelper] Version is v1_15_R1 (11501)
[21:50:05] [Server thread/INFO]: Gh05tt77[/127.0.0.1:60347] logged in with entity id 221 at ([world]-250.83343755367696, 80.04372277152795, 100.82083612284788)
>

**Comment by espidev** [comment]
well there are the issues

**Comment by 007Gh7** [comment]
Gdy wpisałem /ps reload pojawił się błąd ale gdy konsola załadowała wszystko od nowa nie było błędu

**Comment by 007Gh7** [comment]
When I entered / ps reload an error occurred but when the console loaded everything again there was no error

**Comment by espidev** [comment]
send me your messages.yml

**Comment by espidev** [comment]
something is wrong with the configuration here

**Comment by 007Gh7** [comment]
cooldown: '&6Uwaga: &7Poczekaj %time% sekund przed nastepnym postawieniem!'
no_such_command: '&cNie ma takiej komendy. Prosze użyć /ps help po wiecej komend'
no_access: '&cNie możesz tego zrobić!'
no_room_in_inventory: '&cNie masz miejsca w ekwipunku!'
no_room_dropping_on_floor: '&cNie masz miejsca w ekwipunku. Przedmiot leży na ziemi'
invalid_block: '&cNie prawidłowy blok ochrony'
not_enough_money: '&cNie masz wystarczajaco pieniedzy. Cena:$%price%'
paid_money: '&bZaplaciles $%price%'
invalid_world: '&cNie prawidlowy swiat!'
must_be_player: '&cYou must be a player to execute this command.'
go_back_page: Wroc na poprzednia strone.
go_next_page: Idz na nastepna strone.
help: |-
  &8&m=====&r PS Help &8&m=====
  &b> &7/ps help
help_next: '&7Do /ps help %page% aby przejsc na nastepna strone'
command_requires_player_name: '&cKomenda wymaga nazwy gracza.'
no_permission_toggle: '&cNie możesz użyć tej komendy.'
no_permission_create: '&cNie możesz użyć tej komendy.'
no_permission_destroy: '&cNie możesz użyć tej komendy.'
no_permission_members: '&cNie możesz użyć tej komendy.'
no_permission_owners: '&cNie możesz użyć tej komendy.'
no_permission_admin: '&cNie możesz użyć tej komendy.'
no_permission_count: '&cNie możesz użyć tej komendy.'
no_permission_count_others: '&cNie możesz użyć tej komendy.'
no_permission_flags: '&cNie możesz użyć tej komendy.'
no_permission_per_flag: '&cNie możesz użyć tej komendy.'
no_permission_rent: '&cNie możesz użyć tej komendy.'
no_permission_tax: '&cNie możesz użyć tej komendy.'
no_permission_buysell: '&cNie możesz użyć tej komendy.'
no_permission_unhide: '&cNie możesz użyć tej komendy.'
no_permission_hide: '&cNie możesz użyć tej komendy.'
no_permission_info: '&cNie możesz użyć tej komendy.'
no_permission_priority: '&cNie możesz użyć tej komendy.'
no_permission_region: '&cNie możesz użyć tej komendy.'
no_permission_tp: '&cNie możesz użyć tej komendy.'
no_permission_home: '&cNie możesz użyć tej komendy.'
no_permission_unclaim: '&cNie możesz użyć tej komendy.'
no_permission_view: '&cNie możesz użyć tej komendy.'
no_permission_give: '&cNie możesz użyć tej komendy.'
no_permission_get: '&cNie możesz użyć tej komendy.'
no_permission_sethome: '&cNie możesz użyć tej komendy.'
no_permission_list: '&cNie możesz użyć tej komendy.'
no_permission_list_others: '&cNie możesz użyć tej komendy.'
no_permission_name: '&cNie możesz użyć tej komendy.'
no_permission_setparent: '&cNie możesz użyć tej komendy.'
no_permission_setparent_others: '&cNie możesz użyć tej komendy.'
no_permission_merge: '&cNie możesz użyć tej komendy.'
psregion:
  added_to_region: '&b%player%&7 został dodany/-a do działki.'
  added_to_region_specific: '&b%player%&7 został/-a dodany/-a do %region%.'
  removed_from_region: '&b%player%&7 został usunięty z działki'
  removed_from_region_specific: '&b%player%&7 został usunięty z %region%.'
  not_in_region: '&cNie jesteś na terenie działki.'
  player_not_found: '&cNie znaleziono takiego gracza.'
  not_ps_region: '&cNot a protection stones region.'
  region_does_not_exist: '&cRegion nie istnieje.'
  no_regions_owned: '&cNie masz żadnych działek.'
  no_region_permission: '&cNie możesz tego zrobić!.'
  protected: '&bPostawiono działke.'
  no_longer_protected: '&eZniszczono działke.'
  cant_protect_that: '&cNie możesz postawić tutaj działki.'
  reached_region_limit: '&cNie możesz postawić więcej działek (%limit%).'
  reached_per_block_region_limit: '&cWykorzystano limit działek (%limit%).'
  world_denied_create: '&cNie możesz postawić działki w tym świecie.'
  region_overlap: '&cNie możesz ustawić działki tak blisko innego gracza.'
  region_too_close: '&cTwoja działka musi być minimum %num% kratek od innej.'
  cant_teleport: '&cTwój teleport został zablokowany przez działke gracza.'
  specify_id_instead_of_alias: |-
    &7Znaleziono wiele regionów o tej nazwie. Użyj identyfikatora.
     Regiony o tej nazwie: %regions%
  region_not_adjacent: '&cPrzekroczyłeś limit regionów nie sąsiadujących! Spróbuj umieścić
    twój blok ochronny bliżej innych regionów, które już posiadasz.'
  not_overlapping: '&cTen region nie sąsiaduje z innym!'
  multi_region_does_not_exist: Jeden z regionów nie istnieje.'
  no_region_holes: '&cW twoim regionie wykryto niezabezpieczoną przestrzeń! To niedopuszczalne!'
  delete_region_prevented: '&7Region nie może zostać usunięty!'
  not_owner: '&cNie jesteś właścicielem tego regionu.'
  cannot_merge_rented_region: '&cNie można scalić regionów ponieważ %region% jest w czasie wynajmu.'
  no_permission_region_type: '&cNie możesz stworzyć tego regionu.'
  hidden: '&7Blok ochronny jest teraz ukryty.'
  must_be_placed_in_existing_region: '&cPostaw to na istniejącej już działce.'
toggle:
  help: '&b> &7/ps toggle'
  help_desc: Włączanie lub wyłączanie stawiania bloków ochronnych!'
  toggle_on: '&bStawianie bloków ochronnych włączone!'
  toggle_off: '&bStawianie bloków ochronnych wyłączone!'
count:
  count_help: '&b> &7/ps count [player ()opcionalnie()]'
  count_help_desc: Count the number of regions you own or another player.
  personal_region_count: '&7Your region count in this world: &b%num%'
  personal_region_count_merged: '&7- Including each merged region: &b%num%'
  other_region_count: '&7%player%''s region count in this world: &b%num%'
  other_region_count_merged: '&7- Including each merged region: &b%num%'
flag:
  help: '&b> &7/ps flag [flagname] [value|null|default]'
  help_desc: Use this command to set a flag in your protected region.
  flag_set: '&b%flag%&7 flag has been set.'
  flag_not_set: '&b%flag%&7 flag has &cnot&7 been set. Check your values again.'
  gui_header: '&8&m=====&r Flags (click to change) &8&m====='
  gui_hover_set: '&bClick to set.'
  gui_hover_set_text: |-
    &bClick to change.&f
    Current value:
    %value%
  hover_change_group: Click to set this flag to apply to only %group%.
  hover_change_group_null: '&cYou must set this flag to a value before changing the
    group.'
rent:
  help: '&b> &7/ps rent'
  help_desc: Use this command to manage rents (buying and selling).
  help_header: '&8&m=====&r Rent Help &8&m====='
  already_renting: '&cThe region is already being rented out! You must stop leasing
    the region first.'
  not_rented: '&cThis region is not being rented.'
  lease_success: |-
    &bRegion leasing terms set:
    &bPrice: &7%price%
    &bPayment Term: &7%period%
  stopped: '&bLeasing stopped.'
  evicted: '&7Evicted tenant %tenant%.'
  not_renting: '&cThis region is not being rented out to tenants.'
  paid_landlord: '&b%tenant%&7 has paid &b$%price%&7 for renting out &b%region%&7.'
  paid_tenant: '&7Paid &b$%price%&7 to &b%landlord%&7 for region &b%region%&7.'
  renting_landlord: '&b%player%&7 is now renting out region &b%region%&7.'
  renting_tenant: '&7You are now renting out region &b%region%&7 for &b%price%&7 per
    &b%period%&7.'
  not_tenant: '&cYou are not the tenant of this region!'
  tenant_stopped_landlord: '&b%player%&7 has stopped renting out region &b%region%&7.
    It is now available for others to rent.'
  tenant_stopped_tenant: '&bYou have stopped renting out region %region%.'
  being_sold: '&cThe region is being sold! Do /ps sell stop first.'
  evict_no_money_tenant: '&7You have been &cevicted&7 from region &b%region%&7 because
    you do not have enough money (%price%) to pay for rent.'
  evict_no_money_landlord: '&b%tenant%&7 has been &cevicted&7 from region &b%region%&7
    because they are unable to afford rent.'
  cannot_rent_own_region: '&cYou cannot rent your own region!'
  reached_limit: '&cYou''ve reached the limit of regions you are allowed to rent!'
  price_too_low: '&cThe rent price is too low (must be larger than %price%).'
  price_too_high: '&cThe rent price is too high (must be lower than %price%).'
  period_too_short: '&cThe rent period is too short (must be longer than %period%
    seconds).'
  period_too_long: '&cThe rent period is too long (must be shorter than %period% seconds).'
  period_invalid: '&cInvalid period format! Example: 24h for once a day.'
  cannot_break_while_renting: '&cYou cannot break the region when it is being rented
    out.'
tax:
  help: '&b> &7/ps tax'
  help_desc: Użyj tej komendy aby zarządzać i płacić podatki.
  help_header: '&8&m=====&r Taxes Help &8&m====='
  disabled_region: '&cPodatki za ten region są wyłączone'
  set_as_autopayer: '&7Podatki za region &b%region&7 są płacone automatycznie.'
  set_no_autopayer: '&7Podatki za region &b%region&7 są opłacane ręcznie.'
  paid: '&7Koszt &b%region%&7 wynosi &b$%amount%.'
  info_header: '&8&m=====&r Tax Info (click for more info) &8&m====='
  join_msg_pending_payments: |-
    &7Masz &b%money%&7 płatności podatkowych za swoje regiony!'
    Zobacz te płatności /ps tax info
  player_region_info: '&7> &b%region%&7 - &3$%money%'
  player_region_info_autopayer: '&7> &b%region%&7 - &3$%money% &7(zapłacone automatycznie)'
  click_to_show_more_info: Kliknij aby zobaczyć więcej informacji.
  region_info_header: '&8&m=====&r %region% Tax Info &8&m====='
  region_info: |-
    &9Wysokość podatku: &7$%taxrate% (suma za wszystkie regiony)
    &9Czas między cyklami podatkowymi: &7%taxperiod%
    &9Czas na zapłacenie podatku po cyklu: &7%taxpaymentperiod%
    &9Automatyczne płacenie podatków: &7%taxautopayer%
    &9Należne podatki: &7$%taxowed%
  next_page: '&7Wpisz /ps tax info -s %page% aby przejść na nastepną strone!'
buy:
  help: '&b> &7/ps buy'
  help_desc: Kup region na ktorym się aktualnie znajdujesz!
  not_for_sale: '&cTen region nie jest na sprzedaż.'
  stop_sell: '&7Ten region nie jest już na sprzedaż.'
  sold_buyer: '&7Zakup region &b%region%&7 o wartości &b%price%&7 od gracza &b%player%.'
  sold_seller: '&7Sprzedano region &b%region%&7 o wartości &b%price%&7 graczowi &b%player%&7.'
sell:
  help: '&b> &7/ps sell [cena|stop]'
  help_desc: Sprzedaj region na którym się obecnie znajdujesz.'
  rented_out: '&cRegion jest obecnie wynajmowany.'
  for_sale: '&7Region został wystawiony na sprzedaż za &b%price%&7.'
visibility:
  hide_help: '&b> &7/ps hide'
  hide_help_desc: Użyj tej komendy aby pokazać swój blok ochronny.
  unhide_help: '&b> &7/ps unhide'
  unhide_help_desc: Użyj tej komendy aby ukryć swoj blok ochronny.
  already_not_hidden: '&7Blok ochronny nie wydaje się ukryty...'
  already_hidden: '&7Blok ochronny staje się ukryty...'
info:
  help: '&b> &7/ps info members|owners|flags'
  help_desc: Użyj tej komendy aby uzyskać więcej informacji o tym regionie.'
  header: '&8&m=====&r PS Info &8&m====='
  type: '&9Type: &7'
  may_be_merged: (można łączyć z innymi typami)
  merged: '&9Połączone regiony: &7'
  members: '&9Dodani: &7'
  no_members: '&c(no members)'
  owners: '&9Właściciele: &7'
  no_owners: '&c(no owners)'
  flags: '&9Flagi: &7'
  region: '&9Region: &b'
  priority: '&9Priority: &b'
  parent: '&9Parent: &b'
  bounds: '&9Bounds: &b'
  seller: '&9Sprzedający: &7'
  price: '&9Cena: &7'
  tenant: '&9Najemca: &7'
  landlord: '&9Wynajmujący: &7'
  rent: '&9Okres Wynajmu: &7'
  available_for_sale: '&bRegion gotowy na sprzedaż!'
  available_for_rent: '&bRegion gotowy na wynajem!'
priority:
  help: '&b> &7/ps priority [number|null]'
  help_desc: Użyj tej komendy aby nadać swojej działce pierszeństwo!
  info: '&7Priority: %priority%'
  set: '&ePierwszeństwo ustawione!'
  error: '&cError! Spróbować ponownie?'
region:
  help: '&b> &7/ps region [list|remove|disown] [playername]'
  help_desc: Użyj tej komendy aby uzyskać informacje na temat regionów!
  not_found_for_player: '&7Gracz %player% nie posiada działek w tym świecie!'
  list: '&7Działki gracza &b%player%&7: &b%regions%'.
  remove: '&7Gracz &e%player% &7został usunięty!'
  error_search: '&cError! Spróbować ponownie?'
tp:
  help: '&b> &7/ps tp [id/player] [num (optional)]'
  help_desc: Teleportuje cię na jeden z regionów!
  number_above_zero: '&cWpisz liczbę większą od 0'
  valid_number: '&cWpisz poprawną liczbe!'
  only_has_regions: '&c%player% posiada &b%num% &7chronionych regionów!'
  tping: '&aTeleportacja...'
  error_name: '&cError!'
  error_tp: '&cNie znaleziono takiego regionu.'
  in_seconds: '&7Teleportacja nastąpi za &c%seconds%.'
  cancelled_moved: '&cTeleportacja wstrzymana. Nie możesz się ruszać!'
home:
  help: '&b> &7/ps home [name/id]'
  help_desc: Teleportuje cię na jedną z twoich działek!'
  header: '&8&m=====&r Homes (click to teleport) &8&m====='
  click_to_tp: Naciśnij aby się teleportować!
  next_page: '&7Wpisz /ps page -p %page% aby przejść na następną stronę!'
unclaim:
  help: '&b> &7/ps unclaim'
  help_desc: Użyj tej komendy aby zdjąć zabezpieczenie z tego regionu!
view:
  help: '&b> &7/ps view'
  help_desc: Użyj tej komendy aby zwizualizować granice działki.
  cooldown: '&cPoczekaj zanim znów użyjesz /ps view'
  generating: '&7Tworzenie granicy działki...'
  generate_done: '&aGotowe! Granica działki zniknie za 25 sekund!'
  removing: |-
    &bGranica działki znika...
    &aJeśli nadal widzisz bloki spróbuj ponownie się zalogować!
admin:
  help: '&b> &7/ps admin'
  help_desc: Do /ps admin help for more information.
  cleanup_header: |-
    &eCleanup %arg% %days% days
    ================
  cleanup_footer: |-
    &e================
    Completed %arg% cleanup.
  hide_toggled: '&eAll protection stones have been %message% in this world.'
  last_logon: '&e%player% last played %days% days ago.'
  is_banned: '&e%player% is banned.'
  error_parsing: '&cError parsing days, are you sure it is a number?'
  console_world: '&cPlease specify the world as the last parameter.'
  lastlogons_header: |-
    &e%days% Days Plus:
    ================
  lastlogons_line: '&e%player% %time% days'
  lastlogons_footer: |-
    &e================
    %count% Total Players Shown
    %checked% Total Players Checked
reload:
  help: '&b> &7/ps reload'
  help_desc: Reload settings from the config.
  start: '&bReloading config...'
  complete: '&bCompleted config reload!'
addremove:
  help: '&b> &7/ps add|remove [playername]'
  help_desc: Użyj tej komendy aby usunąć lub dodac gracza do działki!
  owner_help: '&b> &7/ps addowner|removeowner [playername]'
  owner_help_desc: Użyj tej komendy aby nadać lub usunąć właściciela działki!
get:
  help: '&b> &7/ps get [block]'
  help_desc: Użyj tej komendy aby dostać lub zakupić blok ochronny(cuboide)
  gotten: '&bBlok ochronny znajduje się w twoim ekwipunku!'
  no_permission_block: '&cNie masz permisji aby użyc tej komendy!'
  header: '&8&m=====&r Protect Blocks (click to get) &8&m====='
  gui_block: '&7> &b%alias% &7- %description% (&f$%price%&7)'
  gui_hover: Naciśnij aby zakupić: &b%alias%
give:
  help: '&b> &7/ps give [block] [player]'
  help_desc: Użyj tej komendy aby nadać komuś blok ochronny!
  given: '&7Nadano &b%block% &7graczowi &b%player%'
  no_inventory_room: '&cGracz nie ma miejsca w ekwipunku!'
sethome:
  help: '&b> &7/ps sethome'
  help_desc: Użyj tej komendy aby ustawić spawn na twojej działce!
  set: '&Dom dla &b%psid% &7został ustawiony w tym miejscu!'
list:
  help: '&b> &7/ps list [player (optional)]'
  help_desc: Use this command to list the regions you, or another player owns.
  header: '&8&m=====&r %player%''s Regions &8&m====='
  owner: '&7Owner of:'
  member: '&7Member of:'
name:
  help: '&b> &7/ps name [name|none]'
  help_desc: Use this command to give a nickname to your region, to make identifying
    your region easier.
  removed: '&7Removed the name for %id%.'
  set_name: '&7Set the name of %id% to &b%name%&7.'
  taken: '&7The region name &b%name%&7 has already been taken! Try another one.'
setparent:
  help: '&b> &7/ps setparent [region|none]'
  help_desc: Use this command to allow this region to inherit properties from another
    region (owners, members, flags, etc.).
  success: '&7Successfully set the parent of &b%id%&7 to &b%parent%&7.'
  success_remove: '&7Successfully removed the parent of &b%id%&7.'
  circular_inheritance: '&cDetected circular inheritance (the parent already inherits
    from this region?). Parent not set.'
merge:
  help: '&b> &7/ps merge'
  help_desc: Użyj tej komendy aby scalić region z innymi regionami!
  disabled: Łączenie regionów jest wyłączone!
  merged: '&bRegiony zostały pomyślnie scalone!'
  header: '&8&m=====&r Merge %region% (Kliknij aby scalić)&8&m====='
  warning: '&7Uwaga!: Scalenie usunie wszystkie ustawienia obecnego regionu!'
  not_allowed: '&cNie możesz scalić tego regionu!'
  into: '&bTen region przylega do innego! Nie możesz go scalić!'
  no_region: '&7Nie znaleziono przylegającego regionu!'
  click_to_merge: Naciśnij aby scalić z %region%!
  auto_merged: '&7Region automatycznie scalony z &b%region%&7.'

**Comment by espidev** [comment]
umm send it on https://pastebin.com

**Comment by 007Gh7** [comment]
https://pastebin.com/XGsxnYVd

**Comment by espidev** [comment]
Okay, on line 222, you have an extra . at the end

**Comment by espidev** [comment]
other than that it looks okay

**Comment by espidev** [comment]
Wait there is more

**Comment by 007Gh7** [comment]
still the messages file changes by itself

**Comment by espidev** [comment]
line 293, you should have wrapped it in '' since there is a colon

```
  gui_hover: 'Naciśnij aby zakupić: &b%alias%'
```

**Comment by 007Gh7** [comment]
Okey works thank you :) And I have a question is there a chance that someday there will be gui?

**Comment by espidev** [comment]
It is in the works for 2.8.0 but it will take some time

**Comment by 007Gh7** [comment]
ah okey :) thanks again

**Comment by espidev** [comment]
np
