### ISSUE TITLE
Players can break the protection block type twice, if breaking the block with Shift + RMB

### ISSUE THREAD

**Issue by workonfire** [espidev/ProtectionStones#168]
There is a bug that allows players to destroy a block that **IS NOT a Protection Stone block**, but a regular block of the same type as the PS block.

For example, if my PS Block is bedrock, players will be able to claim a region, click Shift + RMB on a block of the same type and it would cause breaking the bedrock **and the PS block** (which is bedrock as well). This can be used to grief the edge of the world, if the player claims a region on `Y: 1`

### Examples:
![ezgif com-optimize](https://user-images.githubusercontent.com/34654573/79501216-f5909b80-802d-11ea-9537-0269fbac0f2c.gif)
![ezgif com-optimize (1)](https://user-images.githubusercontent.com/34654573/79501631-a860f980-802e-11ea-9bd4-512cf747dd45.gif)

This issue applies to **every block**, not bedrock only.

**Comment by espidev** [comment]
Please test this build, and let me know if there is an issue: https://ci.espi.dev/job/ProtectionStones/271/

**Comment by workonfire** [comment]
Everything is working great.
