### ISSUE TITLE
Get details of all permissions

### ISSUE THREAD

**Issue by Frithy0** [espidev/ProtectionStones#174]
Could we have the permissions and their details because when I'm on LuckPerm, it shows me a lot but I don't know what it does and I don't have the one with the descriptions (e.g : preciousstone.create)

**Comment by Laarryy** [comment]
https://github.com/espidev/ProtectionStones/wiki/Permissions

**Comment by espidev** [comment]
The wiki page above is correct, and this plugin also is not preciousstones
