### ISSUE TITLE
Log spam WorldGuard region save

### ISSUE THREAD

**Issue by OlekMK342** [espidev/ProtectionStones#175]
Hey, I enable taxes of regions on my server, every 30 seconds I receive a message on the console about updating the region. Can this stop it somehow or is it a plugin error? Nothing was writing on the console before taxes were enabling.
I used:
- WorldGuard [7.0.2]
- ProtectionStones [2.7.3]

Console info:
![spam_WG_PS](https://user-images.githubusercontent.com/61918120/81406177-690f5f80-9139-11ea-8d0b-07e9fa5816ce.PNG)

**Comment by espidev** [comment]
Those are WorldGuard save messages (because the regions are periodically updated for tax updates). Unfortunately I don't think WorldGuard has the option to disable them :(

**Comment by OlekMK342** [comment]
:(
