### ISSUE TITLE
Problem with LWC

### ISSUE THREAD

**Issue by SliderKP** [espidev/ProtectionStones#177]
in my server with protection i using LWC and  users can protect chest in other users protectected area

**Comment by espidev** [comment]
I'm not too familiar with how LWC works, but does it support WorldGuard?

**Comment by SliderKP** [comment]
im not sure, how i can see if lwc support wg?

**Comment by espidev** [comment]
Consider using worldguard's chest locking functionality

**Comment by SliderKP** [comment]
but my new users dont have protection stones

**Comment by espidev** [comment]
WorldGuard allows for using a sign to lock chests

**Comment by SliderKP** [comment]
what i need to type in the sign ?

**Comment by espidev** [comment]
You may want to ask the lwc developers about this actually

Make sure you are using LWC Extended

**Comment by espidev** [comment]
https://worldguard.enginehub.org/en/latest/chest-protection

You need to enable in WG config

**Comment by espidev** [comment]
On second thought, don't use this, there's a warning that this isn't really maintained

**Comment by espidev** [comment]
Ask LWC extended if they have WorldGuard support

**Comment by SliderKP** [comment]
oh lol, i really like the LWC protection, but this is so annoying

**Comment by espidev** [comment]
No update
