### ISSUE TITLE
Suggest to prevent Grieff

### ISSUE THREAD

**Issue by ivandelp** [espidev/ProtectionStones#178]
Could you create a system to avoid grieff in protections?

For example: If the height of the block there are lava flowing or water, set barrier blocks in a block above to prevent enter in the protection.

That could be activated in config.

Example: https://imgur.com/a/zFuYflj

If the protection reach the maximum blocks of minecraft, can't be activated.

**Comment by espidev** [comment]
WorldGuard sort of has this feature, look at the "other recommendations" section for instructions on how to turn it on: https://www.spigotmc.org/resources/protectionstones-updated-for-1-13-1-15-wg7.61797/

**Comment by ivandelp** [comment]
But disable some useful flags

**Comment by espidev** [comment]
Not sure what you mean, it protects against liquid flow

**Comment by espidev** [comment]
No response
