### ISSUE TITLE
Add command to update all the existing regions sizes

### ISSUE THREAD

**Issue by Leonardo-Fiori** [espidev/ProtectionStones#18]
An important feature would be allowing admins to update claim blocks sizes.. maybe if you change your mind a nd you want to make regions taller for example. It would be neat to have something like a /ps admin recreateregions command or something like that to update all regions based on config changes!

Thanks

**Comment by espidev** [comment]
Added in 2.2.0

**Comment by espidev** [comment]
It is /ps admin recreate
