### ISSUE TITLE
block1.toml issues

### ISSUE THREAD

**Issue by Redtile** [espidev/ProtectionStones#180]
Hi I have done exactly as described in the spigot page for copying the .toml file and makeing the block different changing the alias and the size of the protection the description etc, I used notpad to begin with and then when that didnt work I tried with VScode it says its a .toml format and when I upload it to the server the plugin stops working, theres no error in the console it just gives up on life and I cant seem to find anything in the log file either, I /reload my server to check if its working and yes I have rebooted the server too just to make sure it wasnt a weird interaction with the /reload command, I will upload my latest log file if you want to comb over it but I didnt see anything that looked like it was to do with the plugin,
thanks in advance 
Reptile
[latest (1).log](https://github.com/espidev/ProtectionStones/files/4642820/latest.1.log)

**Comment by espidev** [comment]
Try making sure you save as UTF-8 without BOM.

Seems to be related to the issue with the config library I am using.

**Comment by Redtile** [comment]
> Try making sure you save as UTF-8 without BOM.
> 
> Seems to be related to the issue with the config library I am using.

this worked perfect, thank you very much for the suggestion
