### ISSUE TITLE
Cant destroy

### ISSUE THREAD

**Issue by SorinC244** [espidev/ProtectionStones#181]
Hello, i have a problem. My players cant place protect if they are not op. And i have no idea why.

**Comment by espidev** [comment]
Did you give the protectionstones.create permission: https://github.com/espidev/ProtectionStones/wiki/Permissions

**Comment by SorinC244** [comment]
> Did you give the protectionstones.create permission: https://github.com/espidev/ProtectionStones/wiki/Permissions

preciousstones.benefit.create true
yes i did

**Comment by espidev** [comment]
> preciousstones.benefit.create true
> yes i did

This is not PreciousStones, this is ProtectionStones. They are completely separate plugins.

**Comment by SorinC244** [comment]
I downloaded it from here..but i give permissions using LuckPerms

**Comment by espidev** [comment]
> I downloaded it from here..but i give permissions using LuckPerms

Again, the permission is protectionstones.create, not preciousstones.benefit.create...

**Comment by SorinC244** [comment]
Hm, i will try when players leave the server to download again it and see if it work . Thanks . i will be back with updates

**Comment by espidev** [comment]
Please read the permissions page: https://github.com/espidev/ProtectionStones/wiki/Permissions

This plugin has nothing to do with PreciousStones, you gave a PreciousStones permission.
