### ISSUE TITLE
Doors 

### ISSUE THREAD

**Issue by uLyPANNN** [espidev/ProtectionStones#185]
How can I block other players from opening doors/ levers/trapdor in my protection?

**Comment by espidev** [comment]
The interact flag may be what you are looking for: https://worldguard.enginehub.org/en/latest/regions/flags/

**Comment by uLyPANNN** [comment]
wich one ? interact "deny" and use "allow" ?

**Comment by espidev** [comment]
Well to be honest, you don't even need to set flags because by default, WorldGuard already denies it for nonmembers.

**Comment by uLyPANNN** [comment]
on my server other players can walk in my door protection

**Comment by espidev** [comment]
Not sure what you mean, they can enter the region?

**Comment by espidev** [comment]
If you really wanted to make sure, you can set use to deny for nonmembers (/ps flag -g nonmembers use deny)
Or the interact flag if you wish

**Comment by espidev** [comment]
No response
