### ISSUE TITLE
Offset the Protection Stone location relative to the WG area

### ISSUE THREAD

**Issue by Leonardo-Fiori** [espidev/ProtectionStones#19]
A cool feature would be the ability to decenter the position of the claim block.. 
The Protection Stone could have an offset on each axys, with the most important being the Y.

Example: If you want the WG region to appear ABOVE the block, and not in the middle, to avoid wasting claim area underground!

The other suggested feature (/ps admin recreateregions) should take in consideration also this offset..

Thanks again! I've more requests for the future, and im planning to support you more with bigger donations for all the work you are doing for us! Something like custom requests but that would be helpful for everyone :)

**Comment by espidev** [comment]
This will probably make it into 2.3.0

**Comment by espidev** [comment]
Will be in 2.3.0
