### ISSUE TITLE
Does not generate configuration folder

### ISSUE THREAD

**Issue by JUANCO2** [espidev/ProtectionStones#190]
Hello,
I have a problem with the plugin, I install it with the worldgurd and if I put the command / plugins it appears in green and as it works but it does not generate a configuration folder.
Att. Juan

**Comment by JUANCO2** [comment]
Im using the version for 1.16.1

**Comment by espidev** [comment]
Are there any errors in the console? Are you able to see the logs from server startup from ProtectionStones?

**Comment by JUANCO2** [comment]
only this repites 100X 16.07 22:02:24 [Server] Netty Epoll Server IO #2/ERROR java.lang.NullPointerException

**Comment by JUANCO2** [comment]
and yes it says 16.07 22:26:38 [Server] Server thread/INFO Loading ProtectionStones v2.7.5

**Comment by espidev** [comment]
You're going to have to give me more of the error, you just gave me the first line.

**Comment by JUANCO2** [comment]
16.07 22:25:36 [Multicraft] Received start command
16.07 22:25:36 [Multicraft] Loading server properties
16.07 22:25:36 [Multicraft] Starting server!
16.07 22:25:36 [Multicraft] Loaded config for "Spigot 1.16.1"
16.07 22:25:37 [Multicraft] Updating eula.txt file
16.07 22:25:37 [Server] INFO OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=128M; support was removed in 8.0
16.07 22:25:40 [Server] INFO *** Error, this build is outdated ***
16.07 22:25:40 [Server] INFO *** Please download a new build as per instructions from https://www.spigotmc.org/go/outdated-spigot ***
16.07 22:25:40 [Server] INFO *** Server will start in 20 seconds ***
16.07 22:26:00 [Server] INFO Loading libraries, please wait...
16.07 22:26:09 [Server] main/INFO Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
16.07 22:26:10 [Server] main/INFO Reloading ResourceManager: Default
16.07 22:26:12 [Server] Worker-Main-10/INFO Loaded 7 recipes
16.07 22:26:14 [Server] main/INFO Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
16.07 22:26:14 [Server] main/INFO Reloading ResourceManager: Default
16.07 22:26:14 [Server] Worker-Main-10/INFO Loaded 7 recipes
16.07 22:26:14 [Server] Server thread/INFO Starting minecraft server version 1.16.1
16.07 22:26:14 [Server] Server thread/INFO Loading properties
16.07 22:26:15 [Server] Server thread/INFO This server is running CraftBukkit version git-Spigot-758abbe-2b00831 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
16.07 22:26:15 [Server] Server thread/INFO Debug logging is disabled
16.07 22:26:15 [Server] Server thread/INFO Server Ping Player Sample Count: 12
16.07 22:26:15 [Server] Server thread/INFO Using 4 threads for Netty based IO
16.07 22:26:16 [Server] Server thread/INFO Default game type: SURVIVAL
16.07 22:26:16 [Server] Server thread/INFO Generating keypair
16.07 22:26:16 [Server] Server thread/INFO Starting Minecraft server on 45.35.210.53:25582
16.07 22:26:16 [Server] Server thread/INFO Using epoll channel type
16.07 22:26:20 [Server] Server thread/WARN Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
16.07 22:26:34 [Server] Server thread/WARN Legacy plugin Fly v1.0.0 does not specify an api-version.
16.07 22:26:34 [Server] Server thread/WARN Legacy plugin dynmap v3.1-beta-1-367 does not specify an api-version.
16.07 22:26:34 [Server] Server thread/INFO Loading SimpleTpa v3.8
16.07 22:26:34 [Server] Server thread/INFO Loading LuckPerms v5.1.26
16.07 22:26:34 [Server] Server thread/INFO Loading HomePlus v3.9.5
16.07 22:26:34 [Server] Server thread/INFO Loading WorldEdit v7.2.0-beta-02+d10d7d6
16.07 22:26:36 [Server] Server thread/INFO Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@1e706bac]
16.07 22:26:36 [Server] Server thread/INFO Loading DeathCoordinates v1.7.2
16.07 22:26:36 [Server] Server thread/INFO Loading AntiXRay v1.9.0
16.07 22:26:36 [Server] Server thread/INFO Loading AdvancedAchievements v6.1.3
16.07 22:26:36 [Server] Server thread/INFO Loading ImageOnMap v4.0
16.07 22:26:36 [Server] Server thread/INFO Loading BlockLocker v1.8.1
16.07 22:26:36 [Server] Server thread/INFO Loading Fly v1.0.0
16.07 22:26:36 [Server] Server thread/INFO Loading Sleep v1.0.3
16.07 22:26:36 [Server] Server thread/INFO Loading TrollBoss v6.2
16.07 22:26:36 [Server] Server thread/INFO Loading WorldGuard v7.0.4-beta1;bc551da
16.07 22:26:36 [Server] Server thread/INFO Loading ProtocolLib v4.5.1
16.07 22:26:36 [Server] Server thread/WARN Version (MC: 1.16.1) has not yet been tested! Proceed with caution.
16.07 22:26:37 [Server] Server thread/INFO Loading dynmap v3.1-beta-1-367
16.07 22:26:37 [Server] Server thread/INFO version=git-Spigot-758abbe-2b00831 (MC: 1.16.1)
16.07 22:26:38 [Server] Server thread/INFO Mod Support API available
16.07 22:26:38 [Server] Server thread/INFO Loading KeepChunks v1.6.5
16.07 22:26:38 [Server] Server thread/INFO Loading SuperVanish v6.1.6
16.07 22:26:38 [Server] Server thread/INFO Loading ProtectionStones v2.7.5
16.07 22:26:38 [Server] Server thread/INFO Enabling LuckPerms v5.1.26
16.07 22:26:38 [Server] Server thread/INFO __    
16.07 22:26:38 [Server] Server thread/INFO |    |__)   LuckPerms v5.1.26
16.07 22:26:38 [Server] Server thread/INFO |___ |      Running on Bukkit - CraftBukkit
16.07 22:26:38 [Server] Server thread/INFO Loading configuration...
16.07 22:26:38 [Server] Server thread/INFO Loading storage provider... [YAML]
16.07 22:26:38 [Server] Server thread/INFO Loading internal permission managers...
16.07 22:26:39 [Server] Server thread/INFO Performing initial data load...
16.07 22:26:39 [Server] Server thread/INFO Successfully enabled. (took 1155ms)
16.07 22:26:39 [Server] Server thread/INFO Enabling WorldEdit v7.2.0-beta-02+d10d7d6
16.07 22:26:39 [Server] Server thread/INFO WEPIF: Using the Bukkit Permissions API.
16.07 22:26:39 [Server] Server thread/INFO Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_16_R1 as the Bukkit adapter
16.07 22:26:41 [Server] Server thread/WARN ====================================================
16.07 22:26:41 [Server] Server thread/WARN WorldEdit works better if you use Paper 
16.07 22:26:41 [Server] Server thread/WARN as your server software. 
16.07 22:26:41 [Server] Server thread/WARN Paper offers significant performance improvements,
16.07 22:26:41 [Server] Server thread/WARN bug fixes, security enhancements and optional
16.07 22:26:41 [Server] Server thread/WARN features for server owners to enhance their server.
16.07 22:26:41 [Server] Server thread/WARN Paper includes Timings v2, which is significantly
16.07 22:26:41 [Server] Server thread/WARN better at diagnosing lag problems over v1.
16.07 22:26:41 [Server] Server thread/WARN All of your plugins should still work, and the
16.07 22:26:41 [Server] Server thread/WARN Paper community will gladly help you fix any issues.
16.07 22:26:41 [Server] Server thread/WARN Join the Paper Community @ https://papermc.io
16.07 22:26:41 [Server] Server thread/WARN ====================================================
16.07 22:26:41 [Server] Server thread/INFO Enabling BlockLocker v1.8.1
16.07 22:26:41 [Server] Server thread/INFO Enabling ProtocolLib v4.5.1
16.07 22:26:41 [Server] Server thread/INFO Started structure compiler thread.
16.07 22:26:41 [Server] Server thread/WARN **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
16.07 22:26:41 [Server] Server thread/WARN The server will make no attempt to authenticate usernames. Beware.
16.07 22:26:41 [Server] Server thread/WARN While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
16.07 22:26:41 [Server] Server thread/WARN To change this, set "online-mode" to "true" in the server.properties file.
16.07 22:26:41 [Server] Server thread/INFO Preparing level "world"
16.07 22:26:41 [Server] Server thread/INFO -------- World Settings For [world] --------
16.07 22:26:41 [Server] Server thread/INFO Cactus Growth Modifier: 100%
16.07 22:26:41 [Server] Server thread/INFO Cane Growth Modifier: 100%
16.07 22:26:41 [Server] Server thread/INFO Melon Growth Modifier: 100%
16.07 22:26:41 [Server] Server thread/INFO Mushroom Growth Modifier: 100%
16.07 22:26:41 [Server] Server thread/INFO Pumpkin Growth Modifier: 100%
16.07 22:26:42 [Multicraft] Skipped 27 lines due to rate limit (30/s)
16.07 22:26:42 [Server] Server thread/INFO -------- World Settings For [world_nether] --------
16.07 22:26:42 [Server] Server thread/INFO Cactus Growth Modifier: 100%
16.07 22:26:42 [Server] Server thread/INFO Cane Growth Modifier: 100%
16.07 22:26:42 [Server] Server thread/INFO Melon Growth Modifier: 100%
16.07 22:26:42 [Server] Server thread/INFO Mushroom Growth Modifier: 100%
16.07 22:26:42 [Server] Server thread/INFO Pumpkin Growth Modifier: 100%
16.07 22:26:42 [Server] Server thread/INFO Sapling Growth Modifier: 100%
16.07 22:26:42 [Server] Server thread/INFO Beetroot Growth Modifier: 100%
16.07 22:26:42 [Server] Server thread/INFO Carrot Growth Modifier: 100%
16.07 22:26:42 [Server] Server thread/INFO Potato Growth Modifier: 100%
16.07 22:26:42 [Server] Server thread/INFO Wheat Growth Modifier: 100%
16.07 22:26:42 [Server] Server thread/INFO NetherWart Growth Modifier: 100%
16.07 22:26:42 [Server] Server thread/INFO Vine Growth Modifier: 100%
16.07 22:26:42 [Server] Server thread/INFO Cocoa Growth Modifier: 100%
16.07 22:26:42 [Server] Server thread/INFO Bamboo Growth Modifier: 100%
16.07 22:26:42 [Server] Server thread/INFO SweetBerry Growth Modifier: 100%
16.07 22:26:42 [Server] Server thread/INFO Kelp Growth Modifier: 100%

**Comment by espidev** [comment]
This log does not include the part where ProtectionStones initializes. Please give me the section with the [ProtectionStones] prefixed messages.

**Comment by espidev** [comment]
Its likely that your outdated version of spigot is the cause of the issue, please upgrade your spigot with buildtools or use paper: https://papermc.io

**Comment by JUANCO2** [comment]
thanks had a good day/night
