### ISSUE TITLE
Problem when a player change the protection block

### ISSUE THREAD

**Issue by Manugi26** [espidev/ProtectionStones#193]
When a player has a protection and wants to change it for another better he can't do it because the plugin detects the previous protection. For example: If I have a 10x10 protection and I want to upgrade it to a 20x20 protection I can't do it because the 10x10 protection isn't removed.

**Comment by espidev** [comment]
You can simply break and place the protection block, which will apply the new settings.

If you had a large amount of regions, you can use /ps admin recreate

**Comment by Manugi26** [comment]
When I do that it says the same message: "You can not place a protection block here as it overlaps another region"

**Comment by Manugi26** [comment]
Look this please: https://youtu.be/SdWG5Wpysgw

**Comment by espidev** [comment]
Is the new radius overlapping other regions?

**Comment by Manugi26** [comment]
Thank you so much!! It overlaps the spawn region which are protect with WorlsGuard only

**Comment by espidev** [comment]
np
