### ISSUE TITLE
conflict with essentials /skull

### ISSUE THREAD

**Issue by Castiella** [espidev/ProtectionStones#195]
Please read:
https://github.com/EssentialsX/Essentials/issues/3555

I have attempted resetting the config ect

**Comment by espidev** [comment]
Could you please give me your Minecraft version and ProtectionStones version? I am unable to reproduce this issue.

**Comment by Castiella** [comment]
>....=>.... [19:16:33 INFO]: ProtectionStones: 2.7.5
>.... [19:16:33 INFO]: Developers: [EspiDev]
>.... [19:16:33 INFO]: Bukkit: git-Tuinity-"489faf0" (MC: 1.16.1)
>.... [19:16:33 INFO]: WG: 7.0.4-beta1;bc551da

**Comment by espidev** [comment]
Hmm, still unable to produce this issue, could you give me more information about the head you are breaking?

**Comment by Castiella** [comment]
Its any head that belongs to an offline player. Its so baffling. Here is my config:

https://pastebin.com/pn2qnfZM

**Comment by espidev** [comment]
I still don't really know how to reproduce this issue.

I looked at your stacktrace, and simplified some code: https://ci.espi.dev/job/ProtectionStones/280/
Could you let me know if that changes anything?

**Comment by Castiella** [comment]
There is no error in console this time, but theres still a smaller noticeable lag spike. Wondering if it could be ess now?

**Comment by espidev** [comment]
The error in the console was not really an error, it is displayed if the server has not responded for 10 seconds (it just shows what is running)

**Comment by espidev** [comment]
I'll try some other optimizations, but it seems that the lag you experience is from ProtectionStones getting the name of the player that owns the head. Not sure why calling that would lag though.

**Comment by Castiella** [comment]
Since installing this build I have had some really strange essentials issues all of a sudden?
Loss of player data, players loosing inventory upon MOJANG name change?...

**Comment by espidev** [comment]
Umm I literally changed one line of code, which just reduces an extra call to mojang's servers for head data when  breaking a block. That is likely to be unrelated

**Comment by espidev** [comment]
Are you still having issues on the latest version?

**Comment by espidev** [comment]
closing to inactivity
