### ISSUE TITLE
Per block cleanup

### ISSUE THREAD

**Issue by yash-mathur** [espidev/ProtectionStones#196]
Add a way so /ps admin cleanup remove works only on a certain type of claim block.
For example the command could be

/ps admin cleanup remove CLAIM1 5 World

This would help giving players a Noob Plot that will get removed if they are inactive for more than 2 Days and also removing the noob claim.

**Comment by plebexer** [comment]
YES PLZ, i also need that so much.

**Comment by espidev** [comment]
Will be in 2.7.8, if you want it early: https://ci.espi.dev/job/ProtectionStones/302/

`/ps admin cleanup disown [days] [-t typealias (optional)] [world (console)]`

**Comment by plebexer** [comment]
i tried the command and it removed the owner from the protection but it did not remove the protection, i want to remove the protections

**Comment by plebexer** [comment]
how can i delete the protections that dont have owners now?

**Comment by espidev** [comment]
> i tried the command and it removed the owner from the protection but it did not remove the protection, i want to remove the protections

Did you use /ps admin cleanup remove, or /ps admin cleanup disown (you need to use remove)

> how can i delete the protections that dont have owners now?

They should be automatically removed when you run /ps admin cleanup remove

**Comment by plebexer** [comment]
i used disown because you said to use disown
and now i have a lot of disowned protections of inactive players without owners

**Comment by plebexer** [comment]
i will try to do ps admin cleanup remove

**Comment by espidev** [comment]
> i used disown because you said to use disown
> and now i have a lot of disowned protections of inactive players without owners

ah, my mistake.
If you use the remove command it'll remove the empty ones

**Comment by plebexer** [comment]
uhm, i did ps admin cleanup remove and it said cleanup remove 30 days, and it removed one region and i dont know wich region was that, and at first i just wanted to remove regions from an specific type of block so i dont know wich type of region got removed now

**Comment by plebexer** [comment]
i probably have like 200 disowned regions on the world rn and when i did /ps admin cleanup remove, it said it had removed only one region, and there is still more disowned regions in the world

**Comment by espidev** [comment]
> i probably have like 200 disowned regions on the world rn and when i did /ps admin cleanup remove, it said it had removed only one region, and there is still more disowned regions in the world

Very strange, I'll do some more testing, but the only reason I could think of is that the disowned region's block type isn't configured?

**Comment by plebexer** [comment]
any news?, and i did not understand what you meant by disowned region block type

**Comment by espidev** [comment]
oh sorry, i had forgotten about this issue
i'll get to it when I have time

**Comment by espidev** [comment]
Could you send me your regions.yml file (in plugins/WorldGuard/worlds/world), I've been unable to replicate your issues.

**Comment by plebexer** [comment]
Oh! im sorry i have been pretty bussy i just read this, i will send you my regions.tml file

**Comment by plebexer** [comment]
[https://www.mediafire.com/file/bmri40fs82yg7le/regions.yml/file](url)

**Comment by plebexer** [comment]
any news?

**Comment by espidev** [comment]
> any news?

Sorry for taking so long, i was busy and forgot

So it looks like deleting the source blocks of this many regions at once can cause servers to stall, I will attempt a fix to do the source block deletions one by one.

**Comment by espidev** [comment]
Please try the latest build: https://ci.espi.dev/job/ProtectionStones/316/
I've completely reworked the cleanup system which is now a lot more efficient for large amounts of regions.

**Comment by plebexer** [comment]
thanks!, i will try it tomorrow morning as i will do a maintenance on the whole network

**Comment by plebexer** [comment]
it worked :)

**Comment by espidev** [comment]
Cool, it'll make its way into 2.8.0

**Comment by plebexer** [comment]
ok so, something happened, it seems that some protections that i had not set in the command got deleted
because like a month ago i did the disown thing only in some specific protection blocks
so it ended up getting me lots of disowned regions, i did the remove command so the disowned regions disappear in the version you sent me, and now some regions that were not supposed to disappear are not here anymore

**Comment by espidev** [comment]
@plebexer well what *should* happen is that every owner that has not joined within the days you set would get removed from each region's owner list, and if the region has no owners, then the region is removed.

**Comment by plebexer** [comment]
but the point of everything was deleting only some types of protections, because i did not want the big protections to be deleted ever, and that is why i first used the disown command as you told me with the new option you told me to select only some types of protection blocks, but since i used the disown command first then i got protections without owners, and then you told me to use the remove command to delete the disowned regions, but that deleted all types of regions of inactive users ._.

**Comment by espidev** [comment]
@plebexer if the type alias was specified in the command it would have only deleted regions of that type

**Comment by plebexer** [comment]
ok then i did understand wrongly what you said
