### ISSUE TITLE
Zone name is ignored

### ISSUE THREAD

**Issue by HgeX** [espidev/ProtectionStones#200]
Hey! This issue is a bit weird and only occurs on Minecraft 1.16.x. 
`/ps name` command works fine, sets the name of the zone, however it's not possible to teleport to them using their names. *(Altough the flag appears to be set on the WG region)*

Output of `/ps admin version`:
```
[20:16:36 INFO]: ProtectionStones: 2.7.5
[20:16:36 INFO]: Developers: [EspiDev]
[20:16:36 INFO]: Bukkit: git-Paper-136 (MC: 1.16.1)
[20:16:36 INFO]: WG: 7.0.3;5407315 (tried WG-7.0.4 BETA as well, same results)
```

**Comment by espidev** [comment]
So with /ps home or /ps tp? I will do testing shortly

**Comment by espidev** [comment]
Just tested, it seems to work for me...

**Comment by HgeX** [comment]
In theory, `/ps home` is the one that isn't working as expected, but now I'm unable to reproduce it either. Will do a bit more testing... :/

**Comment by HgeX** [comment]
Okay, so at this point I don't know what to say about this. On the main server (which is on 1.16.1) the issue still persists, however on my test server, which as an exact copy of the main, I'm unable to reproduce this bug. The only difference is that the test server is on 1.16.2. Because of this, I'm unsure if this is really an issue with ProtStones, so if you'd like, you can close this ticket. My team is planning on updating the main server to 1.16.2, so we'll see if the issue will be fixed or not...

**Comment by espidev** [comment]
I'll wait until you upgrade to 1.16.2; this is quite strange, not sure what would cause this

**Comment by HgeX** [comment]
Hey. The update is done, the server is now on 1.16.2 a couple of plugins have also been updated, but that's all. The issue is gone. Th I have no idea what might have cause this bug, but at this point I don't even care, because right now the plugin works as it should. :D
