### ISSUE TITLE
/ps home move bug

### ISSUE THREAD

**Issue by J4im3x0** [espidev/ProtectionStones#205]
Hello,

I got lots of reports from the users claiming that /ps home teleport sometimes is cancelled without moving (but PS says that the player moved)

An user sent me this video:
https://youtu.be/s6NLxgRp3tc

Server version: Tuinity (PaperSpigot Fork)1.15.2 
Plugin version: 2.7.5

**Comment by espidev** [comment]
Could you please let me know if this works for you: https://ci.espi.dev/job/ProtectionStones/290/

**Comment by J4im3x0** [comment]
> Could you please let me know if this works for you: https://ci.espi.dev/job/ProtectionStones/290/

I dropped into my production server, but for now not sure if still happening, since the problem just happened sometimes.
I will update you if the problem was solved, thanks

**Comment by espidev** [comment]
No response
