### ISSUE TITLE
TPS issues with protectionstones, what is causing it?

### ISSUE THREAD

**Issue by plebexer** [espidev/ProtectionStones#207]
hi!, i have been using the plugin for at least 10 months now, and i never had problems with tps, but now i was checking the timings and i found that protectionstones is generating some lag related to "BlockPhysicsEvent"
i also know that in my server worldguard is giving lag sometimes because i have enabled the flags water-flow and lava-flow, i want to know if the lag related to protectionstones on the timings could also be caused by that
https://timings.aikar.co/?id=92016c17b8dc4c99aa4ddb0c3e0e93d1#plugins

**Comment by espidev** [comment]
Looking at the timings, it looks like it's Minecraft mainly, it doesn't look like the plugins take up a huge part of the tick. However, I've just looked at the code in ProtectionStones, and the physics event is somewhat inefficient. I can try to optimize it. You can also try disabling worldguard's water-flow and lava-flow.

I'll reply back once I have a build for you that speeds up the physics event for ProtectionStones (though it's unlikely to make a huge impact).

**Comment by espidev** [comment]
Please try this build out: https://ci.espi.dev/job/ProtectionStones/292/
and let me know if it speeds up anything for you. I don't think though that ProtectionStones really impacts the tick that much.

**Comment by plebexer** [comment]
sorry for the delay, i was in the middle of a host change, i will try it

**Comment by plebexer** [comment]
i think it did not get better (anyways i have to other plugins that are giving me lags and im also trying to fix the problems with those)

https://timings.aikar.co/?id=34040cfc801840b097e31b49ae1b2ce6#plugins

**Comment by Legoman99573** [comment]
Only thing I see that would cause it is epicbackpacks based on recent timings report.
![image](https://user-images.githubusercontent.com/7460704/95852524-7f899a80-0d19-11eb-9d16-3783ad85c747.png)
