### ISSUE TITLE
 What would be the format for the permission given to a stone of protection?

### ISSUE THREAD

**Issue by F4brizio** [espidev/ProtectionStones#208]
The following option appears in the forest configuration:
   # Extra permission required to place this specific protection block (you still need protectionstones.create)
     # Also applies to /ps get (you still need protectionstones.get)
     # '' for no extra permission
     permission = 'blockuser'

What would be the extra permission? What format would it have?

¿protectionstones.get.blockuser? It didn't work for me
¿protectionstones.blockuser? It didn't work for me

Any suggestion?

**Comment by espidev** [comment]
It would literally just be "blockuser"

**Comment by F4brizio** [comment]
Thanks, it worked!
