### ISSUE TITLE
config option to default protectionstones placement to be OFF

### ISSUE THREAD

**Issue by spetznack** [espidev/ProtectionStones#210]
We previously used PreciousStones the protectionstones way of protecting players survival homes and we were afraid we had to switch to something entirely different when that plugin was not being updated further.. Until we found protectionstones :O So thank you so much for creating and maintaining this plugin. :D

**Request:** 
Add a config option to default protectionstones placement to be OFF instead of ON for the player when joining the server. 

**Reason:** 
Some of our protectionstone blocks are also decorational blocks which means players are creates a lot of unintentional protectionstones fields because ps placement is default ON when you join the server. 

**Related secondary suggestion:** 
We used Preciousstones for the past 6 years or so and players are used to typing "/ps on" or "/ps off" to enable\disable placement of ps stones. Could these be added to the existing "/ps toggle"? 

Thank you for hearing me out :)

**Comment by espidev** [comment]
I'll see if I can batch this up with some other minor additions for 2.7.8

**Comment by espidev** [comment]
Added the config option default_protection_block_placement_off to config.toml for v2.7.8, if you want it early, get it here: https://ci.espi.dev/job/ProtectionStones/303/
