### ISSUE TITLE
Messages are missing in messages.yml

### ISSUE THREAD

**Issue by sergyops** [espidev/ProtectionStones#211]
I have changed the base command from /ps to /reg in config.toml and now I am changing the /help in messages.yml so that the text it displays is written with /reg and there is no configuration for the help of /reg rent commands and /reg tax.

![image](https://user-images.githubusercontent.com/70977028/97784286-be36a600-1b9d-11eb-97e8-ed36b9fbfaba.png)

**Comment by espidev** [comment]
Thanks for reporting, I'll try to add when I have the time

**Comment by espidev** [comment]
As an alternative, now help messages will reflect the base command set in the config, this will be in v2.7.8
