### ISSUE TITLE
How to give perm to an member on /ps home

### ISSUE THREAD

**Issue by yanndecaii** [espidev/ProtectionStones#217]
i just noticed one of my members tried to put _**/ps home**_ and it says that you cannot do that,you need permissions

**Comment by espidev** [comment]
https://github.com/espidev/ProtectionStones/wiki/Permissions
protectionstones.home

**Comment by yanndecaii** [comment]
but where i put that

**Comment by yanndecaii** [comment]
![image](https://user-images.githubusercontent.com/74616110/99422471-e1808580-28ff-11eb-81f2-7752cb30c04a.png)
Heres what my friend have

**Comment by espidev** [comment]
in your permission plugin

**Comment by yanndecaii** [comment]
in what toml? config or messages?

**Comment by espidev** [comment]
No, your permission plugin, like luckperms

**Comment by yanndecaii** [comment]
oh i dont have that,i have in vault.

**Comment by espidev** [comment]
well the same way you gave other permissions

**Comment by yanndecaii** [comment]
but i dont know how to use vault,and it dosent says any commands

**Comment by espidev** [comment]
how did you give any other permissions then? how are players able to place blocks? that requires a permission...

**Comment by espidev** [comment]
closing to inactivity
