### ISSUE TITLE
distance_between_claims does not work

### ISSUE THREAD

**Issue by Leonardo-Fiori** [espidev/ProtectionStones#22]
As the title says, distance_between_claims is ignored. Latest version, running on Paper 97..

I have a 16x16 claim block, i set distance_between_claims to 20, but players can still place a 16x16 claim near the border of another 16x16 claim.

**Comment by espidev** [comment]
I'm away from home on a trip rn, have you tried with larger distances?

**Comment by Leonardo-Fiori** [comment]
Setting larger distance and restarting the server worked. very strange.
