### ISSUE TITLE
chest protection when renting a region

### ISSUE THREAD

**Issue by sergyops** [espidev/ProtectionStones#222]
They could add a configuration option for when a player rents protection, the owner of that protection can not open their chests also that the items cannot come out through hoppers.

**Comment by Sancires** [comment]
A solution to this would be just to use a separate plugin to handle chest locking, such as [LWCX ](https://www.spigotmc.org/resources/lwc-extended.69551/)or [LockettePro](https://www.spigotmc.org/resources/lockettepro-for-1-14-1-15-1-16.74354/).

**Comment by espidev** [comment]
I agree with the above comment, to use a chest locking plugin as it is much more customizable
