### ISSUE TITLE
BUG: Protectstone dissapear on placing

### ISSUE THREAD

**Issue by Sonlein** [espidev/ProtectionStones#228]
Auto-hide: true
If you place a protectstone, and then place another protectstone in the same place where the old one was without deleting the old region, then the new region will not create, and when the region is unclaimed, the player will receive only one protectstone

**Comment by espidev** [comment]
Let me know if this fixes your issue
https://ci.espi.dev/job/ProtectionStones/314/

**Comment by Sonlein** [comment]
Yes, thanks, it works

**Comment by Sonlein** [comment]
> Let me know if this fixes your issue
> https://ci.espi.dev/job/ProtectionStones/314/

Yes, thanks, it works
