### ISSUE TITLE
/ps home movement detection

### ISSUE THREAD

**Issue by TheGamer497X** [espidev/ProtectionStones#230]
Hello,
Some players when using **/ps home** get their teleportation immediately denied. It says that they have moved, while they haven't moved. It only affects some players, I don't know why is that, there is no specific scenario which makes this happen. I have no idea why only some players are affected by this.

**Comment by espidev** [comment]
It's looking like I can't investigate the issue until february due to schoolwork, sorry about that

**Comment by espidev** [comment]
is this still an issue occurring?

**Comment by itsChix** [comment]
Some people are still facing this issue in my server on version 2.7.7 (I'll update and see if the issue persists)

**Comment by espidev** [comment]
> Some people are still facing this issue in my server on version 2.7.7 (I'll update and see if the issue persists)

I did make a debug build that outputs location information to the console, if you can try it out that'd be great

**Comment by itsChix** [comment]
The bug seems to be fairly rare since it's been a month and no players have reported it again so far. I'll try the dev build if the problem happens again.

**Comment by PlayingWithPi** [comment]
> The bug seems to be fairly rare since it's been a month and no players have reported it again so far. I'll try the dev build if the problem happens again.

Any Updates?

**Comment by itsChix** [comment]
> > The bug seems to be fairly rare since it's been a month and no players have reported it again so far. I'll try the dev build if the problem happens again.
> 
> Any Updates?

Doesn't look like the issue persists. Neither the dev build nor player reports suggest anything.

**Comment by espidev** [comment]
Closing since there have been no more reports of this happening (and I can't duplicate it either)
