### ISSUE TITLE
More PAPI Placeholders

### ISSUE THREAD

**Issue by HySand** [espidev/ProtectionStones#233]
E.G,
Player's number of placed stones                                                     %protectionstones_currentplayer_count%
Whether the player has `number` placed stones                              %protectionstones_currentplayer_has_`number`%
Player's `number`th stone's id                                                           %protectionstones_currentplayer_`number`%
x coordinate of  player’s  `number`th protection stones                   %protectionstones_currentplayer_`number`_localization_x%

It's helpful for custom GUI menus.Thanks.

**Comment by espidev** [comment]
The problem about "numbers" for protection block ids is that order is not guaranteed to be consistent and can change without warning... i can probably make a placeholder though for the ids of the regions that the player owns

**Comment by espidev** [comment]
Added a bunch of new placeholders in https://github.com/espidev/ProtectionStones/commit/51bae63a79c7f59a5cf4d5cc0cbb80109a56dc84

```
- currentplayer_num_of_owned_regions_world
- currentplayer_num_of_accessible_regions_world
- currentplayer_num_of_accessible_regions
- currentplayer_owned_regions_ids_world
- currentplayer_accessible_regions_ids_world
```
