### ISSUE TITLE
Merged regions improper WorldGuard region area

### ISSUE THREAD

**Issue by LKits** [espidev/ProtectionStones#235]
For example, protection stone size 11x11x11

If player places one protection stone at coordinates:
x: 100, y: 100, z: 100
Then protected area is x: 95-105, y: 95-105, z: 95-105

And places another block at:
x: 105, y: 105, z: 105

And merges with another block, then "z" coordinate isn't proper, it goes from 0 to 255 not the way it should be.
So new region would be (and should not be):
x: 95-110, y: 0-255, z: 95-110

I think merging should be reworked so it does NOT remove another WorldGuard region, when merging.
Multiple areas should be still in place and merged info should be separate.
At this moment I restricted merging because of that.

**Comment by espidev** [comment]
WorldGuard unfortunately does not have support for y-levels when doing poly regions so I can only have it go from bedrock to block limit.

**Comment by espidev** [comment]
If you didn't want to do merging, you can look at the alternative, which is /ps setparent (it doesn't delete the old regions)

**Comment by LKits** [comment]
Understood.
Thought I'm not sure why you're even merging WorldGuard regions.
You could have separate config file for merged regions information (for example ps100100100 and ps105105105) and every time any change is being made to one of those merged regions, then change is being made to every merged WorldGuard region. That loop wouldn't be hard to make...

Because then you could have merged together regions AND keep protectionstone region shapes (cuboid for example) merged together.

**Comment by espidev** [comment]
merged regions are precisely for making a single WorldGuard region, trying to mimic and sync several regions together like that doesn't work because they will still be treated as separate regions in code...

what you're describing is also already kind of what /ps setparent does, just using the feature that's already built into worldguard

**Comment by LKits** [comment]
Addparent isn't exactly a good one as well, because then regions must overlap (afaik).
What is one adds protection stone at 95-105 95-105 95-105 and second one at 106-116 106-116 106-116, then merged together it would be 95-116 0 255 95-116.

Anyways, I think reworking merge should be done, because it's not exactly what it should do. 
Maybe "linking" would be better name for it.

I'm not sure why would you even merge WorldGuard regions together like that... keeping separate regions with identical settings (except coordinates of course) would be proper way to go.

Merging together 2 cuboids would have 16 corner points, doesn't matter if they are overlapping or connected "from one corner".
Are you saying that WorldGuard region doesn't support this? Having 3D region with multiple "corner" points?

**Comment by espidev** [comment]
please read about inheritance: https://worldguard.enginehub.org/en/latest/regions/priorities/
you definitely don't need an overlap to use it. 

WorldGuard does not support 3D non-cuboid regions.

**Comment by espidev** [comment]
I am really not interested in maintaining a layer on worldguard, as I'd have to recreate a query system that could go out of sync as soon as any edits are made...
not to mention this would require  rewriting the plugin, and I only have a few minutes a week if I were to even do it...

**Comment by LKits** [comment]
Understood.
Not sure why you'd have to change everything, but then again - it's your "baby" and you know it the best.
I thought it could be done by only changing merge part. Everything else is based on WorldGuard region (and it's "custom" PS flags) anyway.

**Comment by espidev** [comment]
ProtectionStones heavily depends on using single WorldGuard regions internally. With the merge change I'd have to rework every time I use a WorldGuard region, since I have to now be able to treat multiple separate regions as one region. So operations like querying homes, flags, rents, taxes, border viewing, unclaiming, cleanups, etc.
