### ISSUE TITLE
Cleanup command gives error and does not delete regions

### ISSUE THREAD

**Issue by Ilfeus** [espidev/ProtectionStones#24]
[https://pastebin.com/puqcpSs4](https://pastebin.com/puqcpSs4)
When I try to delete inactive regions(/ps admin cleanup remove 10), this error appears. Only the owners are removed in the regions, and the regions itself still exists.

**Comment by espidev** [comment]
Thank you for reporting this bug. The fix should be quick, though I am away on a trip so this may not be fixed immediately.

**Comment by Ilfeus** [comment]
How can I upload it to the plugin? I don't know how to write plugins, etc.

**Comment by espidev** [comment]
Look into creating a pull request, though I've fixed the bug. I'm still away for another week though

**Comment by Ilfeus** [comment]
So I have to wait? I can wait. No problem :D

**Comment by Ilfeus** [comment]
I do not know how to compile, and I do not use github, so I do not know how to use it. I can wait until you "fix" it for such fools as me :P.

**Comment by espidev** [comment]
Sorry, I just need to make sure what I push won't cause any other bugs.

**Comment by espidev** [comment]
Fixed in 2.2.0

**Comment by Ilfeus** [comment]
when 2.2.0?

**Comment by espidev** [comment]
Will be released today
