### ISSUE TITLE
Add feature

### ISSUE THREAD

**Issue by SliderKP** [espidev/ProtectionStones#240]
Good evening, I wanted to consult you if possible and have time to add to the /ps list command that is autocompleted with the tab key

Thank you very much for the support you give and the fabulous plugin that is free,

**Comment by espidev** [comment]
Unfortunately, /ps list with autocomplete might be laggy for large servers due to large amounts of offline players, and rescanning it on every keystroke, which is why I did not enable it.

**Comment by SliderKP** [comment]
and just with the online users? or maybe with an option in config ?

**Comment by espidev** [comment]
possibly with just online users could work

**Comment by SliderKP** [comment]
okey if its possible to add, amazing, and if u want, an option in config to enable or disable if you think this is too laggy, thank you
