### ISSUE TITLE
Proposition

### ISSUE THREAD

**Issue by DiaxManPl** [espidev/ProtectionStones#243]
I have a proposition: the player can use a wooden button and wooden pressure plate on the plot but can't use a stone button and stone pressure plate.

**Comment by espidev** [comment]
um
could you explain again?

**Comment by DiaxManPl** [comment]
A player who is not added to the plot can use wooden elements (wooden buttons, wooden pressure plates, etc.) but can't use stone elements (stone buttons, stone pressure plates, etc.).

**Comment by espidev** [comment]
Huh, that sounds quite strange, which WorldGuard flags do you have set on the region?

**Comment by espidev** [comment]
no response
