### ISSUE TITLE
prevent_teleport_in Not Working

### ISSUE THREAD

**Issue by Chiquis2005** [espidev/ProtectionStones#244]
I have this option activated so that people can't accept tpa in protections and also can't put /sethome but it doesn't work!

**Comment by Chiquis2005** [comment]
hmm?

**Comment by espidev** [comment]
I may have time to look at the issue on Thursday or Friday

**Comment by espidev** [comment]
It works for me...

You don't have the protectionstones.tp.bypassprevent permission do you?

**Comment by espidev** [comment]
closed due to inactivity
