### ISSUE TITLE
Members should also be able to keep a region protected

### ISSUE THREAD

**Issue by DaniFoldi** [espidev/ProtectionStones#245]
Hi!

We're currently implementing this feature where old regions would get deleted - however we would like for members of a regions to also be able to keep a region from getting unclaimed. I believe this should be relatively simple with another for loop, just iterating over the members of a region ([see here](https://github.com/espidev/ProtectionStones/blob/ad1344e99064c54bd7199806ccaa48f03aaa79ed/src/main/java/dev/espi/protectionstones/commands/ArgAdminCleanup.java#L113)).

Probably this could be configurable too - not to change the current default behaviour.

**Comment by espidev** [comment]
The main issue is that if there are no owners, the region cannot be removed.

**Comment by DaniFoldi** [comment]
At least in our case, an admin can sort that out, and regions without owners shouldn't occur anyways.

This is why I had the idea to make it configurable, so for cases where not having an owner is a possibility, member checks could be turned off.

**Comment by espidev** [comment]
I guess it can be a config option, default turned off.

Ping me in a week or two if I forget to look at this issue, I'm quite busy right now.

**Comment by DaniFoldi** [comment]
Hey, a kind reminder as requested 👋

**Comment by espidev** [comment]
I'll try working on this within a few days and give you a build, just got to finish some work first.

**Comment by espidev** [comment]
Please give this build a try: https://ci.espi.dev/job/ProtectionStones/334/

A new config option `cleanup_delete_regions_with_members_but_no_owners` will appear in config.toml, please set it to false.

**Comment by DaniFoldi** [comment]
Hi,

Thanks for the build, it works fine. I'm thinking that maybe members should also be checked if they are active or not? This way the command would still delete regions with members, but ones that are all inactive.

**Comment by espidev** [comment]
Please try 2.8.1, reopen the issue if there are still issues
