### ISSUE TITLE
Spanish message translation update  2.8.1

### ISSUE THREAD

**Issue by RedAngel14Dev** [espidev/ProtectionStones#253]
Hello, I recently downloaded the plugin and as my mother tongue is Spanish Mexico and when I realized that the last translation was missing some translations due to the update, I gave myself the task of translating those missing parts.

[messages.zip](https://github.com/espidev/ProtectionStones/files/6267149/messages.zip)

**Comment by espidev** [comment]
Thank you very much for your work! I will add it when I have the time.

**Comment by espidev** [comment]
I have added it to the page, thanks!
