### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by srrawr11** [espidev/ProtectionStones#257]
Hi basically I'm using PS 1.8.8 for my paper server.

So I want to know if its posible to block the water and lava flow?
For example, I was placed a ps block, then I tried to put water from the top and is still going inside of the protection.. is it posible to block that? I already put the flags water-flow and lava-flow.. but did not working..

Thanks.

**Comment by espidev** [comment]
I don't provide support for v1.8.8

you might want to look at worldguard settings for that because i don't think that has anything to do with protectionstones
