### ISSUE TITLE
/ps info

### ISSUE THREAD

**Issue by SebkowyYT** [espidev/ProtectionStones#262]
Please add the option to delete flags, ec. from command /ps info.

**Comment by espidev** [comment]
Please try this build: https://ci.espi.dev/job/ProtectionStones/353/

In `messages.yml` in the info section, there will be new versions of the messages with the `2` suffix (ex. `flags2`), and so you can customize your messages there. The old versions will be ignored.

**Comment by espidev** [comment]
reopening if there are issues
