### ISSUE TITLE
Problem with perm

### ISSUE THREAD

**Issue by dariopf** [espidev/ProtectionStones#267]
I disabled all bypass perm to the admin group but they can destroy blocks anyway. How can I stop that? Thanks

**Comment by espidev** [comment]
Are you talking about the WorldGuard permission: https://worldguard.enginehub.org/en/latest/permissions/

worldguard.region.bypass.<world> ?

**Comment by dariopf** [comment]
Yes, I turn to false the perm to the group of admins but anyway they can destroy blocks of other users

**Comment by espidev** [comment]
Have you tried without op? You might have to ask worldguard, but it might ignore the permission if the player has op.

**Comment by espidev** [comment]
Closing to inactivity
