### ISSUE TITLE
/ps toggle is great... Would like a /ps on|off as well!

### ISSUE THREAD

**Issue by PlayingWithPi** [espidev/ProtectionStones#269]
/ps toggle is a great option.
Would like to see `/ps on|off` commands (with their own permissions) to boot.

just an easier way to make sure they're on/off rather having to cycle between the toggle to get back to where you started.
Shouldn't be too hard as you already have toggle set up...

Should just be an extension of it, with a specified value being set in the same field.

**Comment by Amelia-exe** [comment]
Is this going to be a thing soon...? @espidev 

Only a small thing, but creature comforts go a long way! :)

**Comment by espidev** [comment]
possibly when i have time maybe this weekend

**Comment by espidev** [comment]
https://ci.espi.dev/job/ProtectionStones/364/

**Comment by Amelia-exe** [comment]
Heya, does this build include the previous update as well, surrounding /ps name only showing the setName or the defaultName?

**Comment by espidev** [comment]
> Heya, does this build include the previous update as well, surrounding /ps name only showing the setName or the defaultName?

yes

**Comment by Amelia-exe** [comment]
Also, I think the naming convention for the file breaks ?

The released .jar file is : ProtectionStones-[version]

Whereas, this one is:
protectionstones-[version]

Just a heads up (:

**Comment by espidev** [comment]
I only rename it to the `ProtectionStones-[version]` scheme when actually doing releases, for legacy reasons (old builds did that, so I just continued).

Usually you are supposed to name projects in lowercase with maven so that's why the build outputs a lowercase one.

**Comment by Amelia-exe** [comment]
Thanks for the quick updates ! 
What's next on the list of things to do ?

**Comment by espidev** [comment]
i'm very short on time these days, so i'm probably going to have to step back

**Comment by Amelia-exe** [comment]
Well thank you for doing these ones really quickly !! 

Very much appreciated, and keep up the good work :)
