### ISSUE TITLE
adding a command to display members

### ISSUE THREAD

**Issue by MastereQ1337** [espidev/ProtectionStones#274]
please add a command to the plugin to display the members and owner of the plot. the command would be to be able to check all the members and know who can do something on it.

basically the command / ps info but it displays the worldguard flags which is average for the player to see it and not very aesthetically pleasing.

(nicknames are green or red because it could be an additional thing that would display whether the player is online or offline. but that's not much of an important thing.)

![obraz_2021-06-26_165303](https://user-images.githubusercontent.com/41511267/123516937-f3e54d80-d69e-11eb-85ef-155c8f12a3e0.png)

**Comment by espidev** [comment]
i mean there is `/ps info owners` and `/ps info members`
