### ISSUE TITLE
Place Limits

### ISSUE THREAD

**Issue by gemgamers** [espidev/ProtectionStones#284]
Hello, How can I limit that how many Protectionstones each player can place?

**Comment by espidev** [comment]
protectionstones.limit.x permission

**Comment by gemgamers** [comment]
That seems to not be an option.On this:  https://www.spigotmc.org/resources/protectionstones-updated-for-1-13-1-17-wg7.61797/

**Comment by espidev** [comment]
It's on the permissions page
https://github.com/espidev/ProtectionStones/wiki/Permissions
