### ISSUE TITLE
Русский перевод/Russian translation 2.8.5 

### ISSUE THREAD

**Issue by TheKi3End** [espidev/ProtectionStones#285]
1. [Messages](https://pastebin.com/gEmCeCeK) 
2. [Config](https://pastebin.com/NBejCF1L)
3. [Block](https://pastebin.com/dmy98v7p)

**Comment by TheKi3End** [comment]
Original color and text.

**Comment by TheKi3End** [comment]
No way to translate /ps admin 
[Скриншот](https://imgur.com/a/qUs6qFZ)

**Comment by espidev** [comment]
Thank you for your hard work!
Yes, at the moment there is no way to translate /ps admin.

**Comment by espidev** [comment]
Added to wiki page
