### ISSUE TITLE
Suggestion: Removing regions after some time of absence

### ISSUE THREAD

**Issue by xR4Z3R** [espidev/ProtectionStones#290]
As in the title. I think that would be nice feature to implement. For example server owners would set in config that when somebody is absent for lets say 1 month all of his regions would be automatically removed. This would prevent unnecessery land claims by other players who would leave the game and never come back

**Comment by espidev** [comment]
Use the command `/ps admin cleanup remove [days since last join]` ex. `/ps admin cleanup remove 30`

**Comment by xR4Z3R** [comment]
Ohh thank you hahah
