### ISSUE TITLE
Dupe with a Wither Boss please fix

### ISSUE THREAD

**Issue by Koosi341** [espidev/ProtectionStones#296]
I was creating a project and ran into a problem. If Wither Boss breaks the private block. Then it is either a dead end (/ unhide command), or the protected area will not be removed. More details in the video. https://youtu.be/9OVbZKd5B-I

**Comment by espidev** [comment]
do you have destroy_region_when_explode set to true or prevent_explode set to true in the block config

**Comment by Koosi341** [comment]
> do you have destroy_region_when_explode set to true or prevent_explode set to true in the block config

It did't help. https://imgur.com/a/4PQ2ep0

**Comment by espidev** [comment]
could you please send your configs here

**Comment by Koosi341** [comment]
block: https://pastein.ru/t/w3v
config: https://pastein.ru/t/33v

**Comment by Koosi341** [comment]
With dinomite, everything works fine, the block and protection are in place.

**Comment by espidev** [comment]
Should be fixed in https://ci.espi.dev/job/ProtectionStones/390/ (1.17 only)
