### ISSUE TITLE
Fly Flag Bug

### ISSUE THREAD

**Issue by DonPanda312** [espidev/ProtectionStones#298]
The player on my server found bug with fly on cuboid with anti-logout.
I will describe it in the steps below:

Place cuboid
Turn on Fly flag on cuboid
Delete cuboid by commad or hand.
Get attacked by player
Wait until the anti-logout is over
Place cuboid again.
Get fly bug(work on all world, not only for cuboid)
Contact with me on discord:
QuestionCatcher#9876

EDIT1:This bug was confirmed by ppl from the admin team so this player didn't have any cheats etc.

**Comment by espidev** [comment]
Could you please record a video of doing this? As well as what kind of anti-logout plugin you are using, I don't know how I'm going to test for it otherwise.

**Comment by DonPanda312** [comment]
Anti-logout plugin - CombatLogX
link to his perspective: https://www.youtube.com/watch?v=gLHT7FkYrAE
Działka = enternig on player couboid
Opuszczasz działkę gracza = leaving the player cuboid.

**Comment by espidev** [comment]
Thank you, I will debug

**Comment by espidev** [comment]
Resolved offline
