### ISSUE TITLE
Glow

### ISSUE THREAD

**Issue by m4kii420** [espidev/ProtectionStones#299]
Is it possible to make protection block to glow?

**Comment by espidev** [comment]
I'm not sure how useful this is... it'd be pretty annoying to add because it would likely require NMS, breaking forward compatibility for future minecraft versions

**Comment by m4kii420** [comment]
On our survival server players get one protection stone on join but usually, they don't notice it in their inventory :/

**Comment by m4kii420** [comment]
But it's ok, I was just wondering is that possible.

**Comment by Amelia-exe** [comment]
> On our survival server players get one protection stone on join but usually, they don't notice it in their inventory :/

Rename the item, and add some info in the lore. It's up to them to read and understand it. 

Don't break compatibility because of user stupidity

**Comment by espidev** [comment]
Closing due to infeasibility
