### ISSUE TITLE
chest-access and interact issue

### ISSUE THREAD

**Issue by dex2code** [espidev/ProtectionStones#300]
Hello friends!

I have Spigot 1.16.5 + World Guard 7.0.5 + ProtectionStones 2.8.5

My idea is to prevent other players from destroying and placing blocks inside the private area, as well as opening doors and chests.

Everything is ok with blocks. Owner can place and destroy the block inside the private region but other players cannot. Fine.

But I faced the issue that other players can open the doors and chests as well as steel everything from the chest.

I edited block1.toml config file and added the following lines into the 'flags' section:

"interact deny",
"chest-access deny"

After 'ps reload' command and creating new private region I faced that nobody can open the door and chest inside the private area, including the owner of this region.

I also tried to specify additional rules for owner like:

"interact deny",
"-g owners interact allow"

but it seems that only last rule is applying for region globally.

Did you face the same problem and how you solved this?

Thanks!

**Comment by dex2code** [comment]
Well, I found the way to solve this by adding the following rules into the 'flags' section:

"-g nonmembers chest-access deny"
"-g nonmembers interact deny"

It works fine )

**Comment by Amelia-exe** [comment]
@espidev can these flags be added as default?

**Comment by espidev** [comment]
> @espidev can these flags be added as default?

This is already the default behaviour with WorldGuard, I'm guessing in this case here the global worldguard region had flags set, which might've been inherited

I guess I can add it as default
