### ISSUE TITLE
An error

### ISSUE THREAD

**Issue by dh3b** [espidev/ProtectionStones#303]
I'm running my server on 1.18, but when i run protection stones 2.9.0 it gives this [error](https://pastebin.com/EdaXyqFY). It happens every time when i run my server either reload it. Non of the in game commands are accessible.

Can somebody help?

**Comment by espidev** [comment]
It seems in your configs, a field that requires a floating point number (with decimal), is missing the .0 after

**Comment by espidev** [comment]
Its probably something like `price`

**Comment by dh3b** [comment]
Thank you so much, it worked
