### ISSUE TITLE
Can't create adjacent claim even though it's the same owner

### ISSUE THREAD

**Issue by stosdenfer** [espidev/ProtectionStones#304]
Hi! I have a server in offline mode. I have this in my  config
`regions_must_be_adjacent = true` | config.toml
`distance_between_claims = 128` | block1.toml

When a player claims their first chunk, it goes great. But when they try to claim the chunk next to it, they get the error: **Your protection block must be a minimum of 128 block from the edge of other regions!** even though they are the owner of the adjacent region. Here are my config files on *pastebin*:
https://pastebin.com/5z8d98r1
https://pastebin.com/T0fmqJHF

I'm on paper build 101 and plugin version 2.9.0. Configs are fresh, not updated! 

Thanks!

**Comment by espidev** [comment]
Fixed by https://github.com/espidev/ProtectionStones/commit/534ba261b706d6f3cbf2c94c5da09d5f3272b519
