### ISSUE TITLE
Suggestion: Allow placement on passthrough deny

### ISSUE THREAD

**Issue by EvilOlaf** [espidev/ProtectionStones#306]
Hey there,

I have a simple testing setup here with WE, WG, LP and ProtectionStones.
I would like to allow building in player regions only. Therefore *passthrough* is set to *deny* on global.
Player should be able to create their own regions whereever they want by utilising ProtectionStones.

The issue is that *passthrough* obviously prevents block-place. 

I asked at EngineHub if there is a way to work around this but they state that there is "not really" one.
Either use something else that does not depend on block-place or come up with something that allows bypass that protections.

Very cool from you to keep this plugin alive :)

Thanks for reading.

Cheers
Werner

**Comment by espidev** [comment]
I don't have any guarantees that this will be done any time soon, but this is one of the most requested features

**Comment by espidev** [comment]
Will be in v2.10.0
