### ISSUE TITLE
Water is explosion-proof

### ISSUE THREAD

**Issue by HoYa-DaiBo** [espidev/ProtectionStones#31]
I just tested with my friends.
If you place water in the protection block area
TNT will not be able to blow up the area
Is there any way to prevent this from happening?
(This is just a problem, if there is no solution, it doesn't matter)

**Comment by espidev** [comment]
Hmmm well this is part of Minecraft physics. I think people use tnt cannons with sand to go around this. There might be another plugin that allows tnt to blow up under water.

**Comment by HoYa-DaiBo** [comment]
Ok thank you!
