### ISSUE TITLE
Adding a player with Protectionstones.limit permission doesn't work when offline

### ISSUE THREAD

**Issue by UnitedCraft** [espidev/ProtectionStones#311]
A player that has the "Protectionstones.limit.1" permissions can add it as /ps addowner when offline.

In this way, the limit is bypassed and such a player can have an unlimited amount of protectionstones that he owns.

When a player is online, it works fine.

The latest version of ProtectionStones from Jenkins, and server version purpur 1.18.1 (latest build)

**Comment by espidev** [comment]
Hmm, I seem to be unable to reproduce this issue, I get the message "This player has reached their region limit.". What does /ps count [user] say for the player? They don't have op or anything like that right?

**Comment by UnitedCraft** [comment]
> Hmm, I seem to be unable to reproduce this issue, I get the message "This player has reached their region limit.". What does /ps count [user] say for the player? They don't have op or anything like that right?

I have the op and I can add as am owner of offline default player, when he came online I can't, because of the limit.

**Comment by espidev** [comment]
When the server starts up, is there this message: `[ProtectionStones] LuckPerms support enabled!`

**Comment by UnitedCraft** [comment]
> When the server starts up, is there this message: `[ProtectionStones] LuckPerms support enabled!`

Yes there is a message. But try to create that. 1 player is online and the second one is offline, and then try to add him as an owner. I have also option - members are able to teleport

**Comment by espidev** [comment]
> 1 player is online and the second one is offline, and then try to add him as an owner

Yes, I've tried that and I get the `This player has reached their region limit.` message, have you checked the player's owned region count with /ps count?

I'm quite confused as to how this can occur.

**Comment by UnitedCraft** [comment]
> > 1 player is online and the second one is offline, and then try to add him as an owner
> 
> Yes, I've tried that and I get the `This player has reached their region limit.` message, have you checked the player's owned region count with /ps count?
> 
> I'm quite confused as to how this can occur.

Yes, ps count of this player is 3, and that is the permission limit of 3. But when he are online I cant add him to several protection regions, when he gets offline I can...

**Comment by UnitedCraft** [comment]
> > 1 player is online and the second one is offline, and then try to add him as an owner
> 
> Yes, I've tried that and I get the `This player has reached their region limit.` message, have you checked the player's owned region count with /ps count?
> 
> I'm quite confused as to how this can occur.

Look at this:
https://streamable.com/11bfk7

**Comment by espidev** [comment]
Could you please turn on debug (/ps admin debug) and give me the console output when you try?

**Comment by UnitedCraft** [comment]
> Could you please turn on debug (/ps admin debug) and give me the console output when you try?

I have turned on but nothing shows in console, only my commands

**Comment by UnitedCraft** [comment]
> Could you please turn on debug (/ps admin debug) and give me the console output when you try?

When the players is online:
`[02:06:05 INFO]: RavenskyPaul issued server command: /ps addowner Testerka
[02:06:05 INFO]: [ProtectionStones] [DEBUG] Debug limits for: Testerka
[02:06:05 INFO]: [ProtectionStones] [DEBUG] Region ps-4816x65y-3815z (world world) (type Działka)
[02:06:05 INFO]: [ProtectionStones] [DEBUG] Region ps-4711x63y-3829z (world world) (type Działka)
[02:06:05 INFO]: [ProtectionStones] [DEBUG] Region ps-4633x64y-3754z (world world) (type Działka)
[02:06:05 INFO]: [ProtectionStones] [DEBUG] Region ps-4845x69y-3954z (world world) (type Działka)
[02:06:05 INFO]: [ProtectionStones] [DEBUG] Region ps-4899x62y-3791z (world world) (type Działka)
[02:06:05 INFO]: [ProtectionStones] [DEBUG] Adding region type Działka.
[02:06:05 INFO]: [ProtectionStones] [DEBUG] Of type Działka: player will have 6 regions - Player's limit is 3 regions.`

When the player is offline
`[02:06:55 INFO]: RavenskyPaul issued server command: /ps addowner Testerka`

And he is succesfully added nothing more messages in console
