### ISSUE TITLE
When I break the block

### ISSUE THREAD

**Issue by jlescalonap** [espidev/ProtectionStones#314]
Hi, sorry for this noob question but I've been searching around and didn't find an answer so I decided to come and ask...

When I break the block, the protected zone should get unprotected and the block that returns to my inventory should be the protected stone that I'd placed before, but the protected zone remains protected and the block that comes into my inventory is a common block and not the protection one... what should I do?, thanks for reading.

**Comment by espidev** [comment]
Are there errors in the console when breaking the block? What happens if you do `/ps unclaim` instead?

**Comment by jlescalonap** [comment]
When I use /ps unclaim it works, I've found out that the block only don't returns to my inventory when I'm using super pick as OP

**Comment by espidev** [comment]
Hmm, if you're using some custom plugin it's possible that it's bypassing the event, so ProtectionStones becomes unable to pick it up. Could you please try this developer build, I believe I added something that may resolve it recently: https://build.espi.dev/job/ProtectionStones/398/artifact/target/protectionstones-2.9.1.jar

**Comment by jlescalonap** [comment]
Thank you!
