### ISSUE TITLE
Placeholder for whether /ps toggle is enabled

### ISSUE THREAD

**Issue by yellow-pillow** [espidev/ProtectionStones#315]
Hi, cool plugin, you're good!

It's a pity you don't update and support versions for 1.16 and so on anymore, but at least let my idea appear on new versions of the plugin!

Anyway, I was sitting here and I got the genius idea to make a full-fledged menu for protectionstones!

I do not suggest that you make a menu, because everyone can make it separately with delux menus, etc.

I would like to suggest adding MORE placeholders

for example for /ps toggle - on/off placeholder

**Comment by espidev** [comment]
Added in v2.10.0
