### ISSUE TITLE
Hungarian translation - 2.9.1

### ISSUE THREAD

**Issue by Victor75007** [espidev/ProtectionStones#316]
Hello,
I recently finished with the PS translation.
Currently no hungarian translation has been submitted yet.
Many servers in Hungary use this plugin, so I was a little surprised that no one has submitted the translation.

This is the messages.yml file only.

Lanuage: Hungarian (hu_hu)
https://pastebin.com/VLJWAtb0

And thank you for your work. :)

**Comment by espidev** [comment]
Hi, thank you so much for the translation contribution!

It has been added on the translations page.
