### ISSUE TITLE
Unlimited XP with a grindstone

### ISSUE THREAD

**Issue by m4kii420** [espidev/ProtectionStones#324]
I didn't even know about grindstone until one player showed me this bug.
So if the player has an enchanted protection stone he can put it into a grindstone and remove enchantments from it. This will give him good amount of xp and he can just place it down and destroy it to get a new enchanted one and then repeat the process.

**Comment by espidev** [comment]
Please try this build https://build.espi.dev/job/ProtectionStones/415/

**Comment by m4kii420** [comment]
that's it, works great
