### ISSUE TITLE
Feature Request - Custom Model Data

### ISSUE THREAD

**Issue by Yajsam** [espidev/ProtectionStones#325]
Blocks loading custom model data tag would be amazing. 

Maybe the config could be like 
type = 'PAPER#10036"

**Comment by espidev** [comment]
What can this be used for? I haven't actually heard about what this is 😅

**Comment by Yajsam** [comment]
Sorry I gave a really poor example.

So custom model data allows the block to load a custom texture from a resource pack. Included 3d models.

Say you set the block to a... diamond block, but the diamond block loads custom model data, stored in the nbt, it would load a side texture for the item but still be a diamond block. 

Custom model data is being used for all sorts of things like furniture even with plugins such as itemadder. 

I'm not sure I'm explaining myself well, I could send some screen shots in the M.O.S.S discord sometime if you'd like?

**Comment by espidev** [comment]
I think I got the idea, I'll look into it over the weekend

**Comment by espidev** [comment]
Please try https://ci.espi.dev/job/ProtectionStones/421/

**Comment by Aitooor** [comment]
You cannot use the same Material with different Custom Model Data (which is done a lot, for example with PAPER)

Logs: https://paste.md-5.net/nezejecoji.md
