### ISSUE TITLE
strange counting of plots

### ISSUE THREAD

**Issue by Kocimietka7192** [espidev/ProtectionStones#328]
![image](https://user-images.githubusercontent.com/83091816/171995693-19099907-748d-4f9d-9efc-47f89c5419e2.png)
Hi, I have a problem - the player is not added to this plot and the / ps list <nick> says he is.
![image](https://user-images.githubusercontent.com/83091816/171995883-01a8258b-dec4-420c-bcc1-9ad8e208c125.png)
here it says that it has 8 parcels merged - but for China I can not find them using the / ps cords list <nick>

**Comment by espidev** [comment]
I am kind of confused on the question, but if a player is an owner or member of a plot /ps list will show them being part of the plot.

**Comment by Kociak7331** [comment]
will write again, the player is not added to this plot - and in "ps list" I say that he is.

In addition, in "/ps list" he says that the player has two plots and he cannot create more plots even though I have set a limit for this person to 8 plots

**Comment by espidev** [comment]
I think it's worth trying /rg info on the region to see if the members and owners list is the same? I've never had a report of the count just straight being wrong...

You can also try turning on /ps admin debug and checking the console, and see if the regions are correct when the error message comes up (try to hit the limit).

**Comment by espidev** [comment]
closed to inactivity
