### ISSUE TITLE
rg flag <name> -g members fly allow

### ISSUE THREAD

**Issue by Wersebu** [espidev/ProtectionStones#335]
Hello i aded flag to player plot and its works ok but when i add it to plot in Nether or end its not working when player is teleporting via /home he need to be on plot reload and then its working or tp clouse to plot and go there by feet but ustin /home its not working 

Command i use 
/rg flag ps4372x53y3083z -g members fly allow

**Comment by espidev** [comment]
I am very confused about the sentence, could you please try to rephrase it?

**Comment by Wersebu** [comment]
Fly is working fine if he is in nether and move to his pv by walking
but if he whonts to tp from overworld to nether ps his fly is not working

**Comment by espidev** [comment]
I'm not sure if this really has anything to do with ProtectionStones, please check your worldguard configuration

**Comment by espidev** [comment]
Closed to inactivity
