### ISSUE TITLE
ProtectionsStones on the map with flag block-place=deny

### ISSUE THREAD

**Issue by woojtek252** [espidev/ProtectionStones#337]
Hi. 
I would like to make it possible to put a protection-block
on the map with the flag:

**"block-place=deny"** and **"block-break=deny"** 
I want the players not to destroy the map, but at the same time to be able to have theirs cuboid.
It is possible?

**Comment by espidev** [comment]
Apologies for the delay, my email notifications are a complete disaster...

In the block config enable the `placing_bypasses_wg_passthrough` option. Then set worldguard passthrough to false on the world and it should work.

**Comment by espidev** [comment]
closed to inactivity
