### ISSUE TITLE
One region can overlap another

### ISSUE THREAD

**Issue by OlegiTL** [espidev/ProtectionStones#338]
Player 1, placed a region 16x16 and on the soma border of this region, player 2 set a region 100x100 and completely blocked the region of player 1,
and 1 and 2 player can't do anything on the 16x16 region. I climbed the whole config, I don’t know what to do and how to fix it, what would it be like to use ordinary regions, what would it be like to put 100x100 in the chat “There is a region on the territory of 100x100” how to do this?

**Comment by espidev** [comment]
Are both player 1 and player 2 owners of the 16x16 region? If player 2 isn't, it shouldn't be possible for them to overlap

**Comment by OlegiTL** [comment]
> Are both player 1 and player 2 owners of the 16x16 region? If player 2 isn't, it shouldn't be possible for them to overlap

player 2 is not in the 16x16 region. but if he puts a block on the very border of the region of player 1, then it overlaps the region 16x16

**Comment by OlegiTL** [comment]
I found the reason. The problem was permissions.
