### ISSUE TITLE
ps home not work

### ISSUE THREAD

**Issue by Kocimietka7192** [espidev/ProtectionStones#339]
![image](https://user-images.githubusercontent.com/83091816/179213326-a330aa91-f1d4-45e0-be1a-93cfd4bc3f4c.png)
Doesn't work / ps home - I tried to debug something but nothing came out. The above-mentioned message pops up (the error occurs since the update on spigomc (2.10.3)) on the previous one everything worked;) (2.10.2)

**Comment by espidev** [comment]
Hi, were you using development builds? This may fix it: https://build.espi.dev/job/ProtectionStones/426/

**Comment by espidev** [comment]
Closed to inactivity
