### ISSUE TITLE
i cant limit protections

### ISSUE THREAD

**Issue by ShaunaFurry** [espidev/ProtectionStones#340]
im trying to use 
protectionstones.limit.x
protectionstones.limit.world.x
and not working in 1.18.2

**Comment by Elektrus** [comment]
It's not a command, it's a permission for a manager like luckperms. X should also be replaced by a number in case it wasn't clear.

**Comment by ShaunaFurry** [comment]
yes i put on luckperms
"/lp group default permission set protectionstones.limit.4"
and user can put more than 4 no have a limit

**Comment by Elektrus** [comment]
You need to specify the state at the end.
lp group default permission set protectionstones.limit.4 true

**Comment by ShaunaFurry** [comment]
still not working

**Comment by espidev** [comment]
Make sure you are testing without `protectionstones.admin` permission and op, otherwise it will override.

**Comment by ShaunaFurry** [comment]
my players no have protectionstone.admin or op

**Comment by espidev** [comment]
I can't reproduce this issue, so you'll need to check if your permissions are being applied properly to users.

**Comment by ShaunaFurry** [comment]
![image](https://user-images.githubusercontent.com/45226984/182462338-b0af24c5-32f6-4278-8be3-ae4b11834eef.png)

**Comment by espidev** [comment]
Perhaps you should try turning on /ps admin debug and viewing the console after placing a block

**Comment by espidev** [comment]
closed to inactivity
