### ISSUE TITLE
Color Bug In Protection Message

### ISSUE THREAD

**Issue by Zsomi4** [espidev/ProtectionStones#343]
When you enter an area, the message displays the wrong color code.

![unknown](https://user-images.githubusercontent.com/97435387/182558301-85cb910f-1d32-46ee-b75d-91947505d472.png)

![unknown (1)](https://user-images.githubusercontent.com/97435387/182558402-7965d753-09f8-49cb-bf01-e6ed294d5850.png)

Protection Block config: https://pastebin.com/WEWt5ksX

**Comment by espidev** [comment]
Hmm, that's up to your flag configuration and worldguard... does /ps info show the issue and can you set the flag manually?

**Comment by espidev** [comment]
Looking at your configuration, perhaps try using '&' instead of §

**Comment by espidev** [comment]
closed to inactivity
