### ISSUE TITLE
region height

### ISSUE THREAD

**Issue by crazzymen** [espidev/ProtectionStones#359]
Hello. I have a problem with the height of plots.
The plot protects up to level 256 and up to level -1 despite the fact that I have set it to -1 in the block config

"	# Minimum distance between claims (that aren't owned by the same owner), measured from the protection block to the edge of another region
	# You will probably have to change this between blocks, since the region sizes will be different
	# Set to -1 for no minimum, but will still check for overlapping regions
	distance_between_claims = -1
	# Protection radius of block (radius of 64 -> 129 x 129 region)
	# Set y_radius to -1 if you want it to protect for all y levels.
	# y_radius must be -1 if you are allowing the region to be merged ("allow_merging" option)
	x_radius = 25
	y_radius = -1
	z_radius = 25"

Is it possible to make a region protect the terrain to the maximum level up and down?

**Comment by espidev** [comment]
Which version are you using here? This works from my testing properly.

Feel free to reopen if this is still an issue
