### ISSUE TITLE
Food dupe in protected Areas

### ISSUE THREAD

**Issue by lChrisjm** [espidev/ProtectionStones#363]
Greetings, I would like to report a bug, this is that when an area is protected, users who are not members of that area can infinitely duplicate crops in these circumstances:

1- The user must not be a member of the protected region.
2- There must be little lighting in the protected area.
3- The user must have a bed.

To replicate the bug, just plant any crop, make or wait for it to grow and once done, remove the light and place the bed over the crop.

It will not allow the bed to be placed and at the same time it will remove the crop from the area and replant it automatically, by repeating this process you can get the crop infinitely.
![imagen](https://user-images.githubusercontent.com/43703371/229668336-da0aed30-9d3a-44e7-b1c9-16c1956ca0cf.png)

**Comment by espidev** [comment]
This sounds like something you should try to reproduce with a regular worldguard region, and if it still exists, report to worldguard (since protectionstones doesn't handle this)

**Comment by legendofgow** [comment]
This is spigot bug, not protectionsstones or worldguad, you need to find plugin to fix this, or update the server version
