### ISSUE TITLE
Only admins can place private blocks

### ISSUE THREAD

**Issue by Lemonomon** [espidev/ProtectionStones#365]
I don't know how to make that players can place blocks. Just writes that they don't have permission to place private blocks. Please, can somebody help me understand how to fix that?

**Comment by espidev** [comment]
Give the correct permissions: https://github.com/espidev/ProtectionStones/wiki/Permissions

**Comment by Lemonomon** [comment]
Like this?
![image](https://user-images.githubusercontent.com/130449103/231595524-8f7104e6-7c17-4ce9-9e0e-dd6811b25138.png)
