### ISSUE TITLE
ProtectionStones + PvpManager

### ISSUE THREAD

**Issue by frogglen** [espidev/ProtectionStones#366]
pvpmanager plugin developer and I found a possible bug in his plugin, when 2 pvp enabled players are inside a protection, the owner of the protection can start PVP, but the one who is not owner of the protection can not start pvp, when the owner of the protection attacks the other player is tagged and at that moment is when he can fight against the player who owns the region.

https://github.com/ChanceSD/PvPManager

**Comment by espidev** [comment]
This was responded to in the discord server, the pvp plugin should check worldguard support
