### ISSUE TITLE
I didn't understand where I need to write permission for players

### ISSUE THREAD

**Issue by Lemonomon** [espidev/ProtectionStones#370]
Sorry, but can you show me all stapes which I need to do that players can place protection block? I understood not much what somebody say about this. If I understood all with your help, then thanks so much.

**Comment by vBagieta** [comment]
You can set this in your block configuration file (example: block1.toml) 
[player]
...
    permission = ''permission.to.place.this.block"

**Comment by Lemonomon** [comment]
Nothing changed. Still doesn't work.

**Comment by espidev** [comment]
You need to give the protectionstones.create permission to players using a permission plugin, like LuckPerms
