### ISSUE TITLE
Can't find protectionstones limit

### ISSUE THREAD

**Issue by Lemonomon** [espidev/ProtectionStones#375]
In the lp I didn't find the protectionstones limit. Maybe I have different version of this plugin, so what i should do to limit private blocks placement?
![image](https://user-images.githubusercontent.com/130449103/236626895-3a9f83c1-ba6d-498f-9eab-e1919f0ecfb0.png)

**Comment by espidev** [comment]
It is not listed there because there is no set permission, you have to specify a number manually, for example:
`protectionstones.limit.1`, `protectionstones.limit.5`, etc.
