### ISSUE TITLE
pistons doesnt working in a custom protected block

### ISSUE THREAD

**Issue by jonander2233** [espidev/ProtectionStones#38]
![2019-07-31_06 03 29](https://user-images.githubusercontent.com/53497678/62171384-fe82f500-b358-11e9-9046-bfb3a6452935.png)

**Comment by espidev** [comment]
You can change this in the config

**Comment by jonander2233** [comment]
i tryed typing false on true but not works

**Comment by jonander2233** [comment]
if i quit cube works

**Comment by espidev** [comment]
I'm not sure if I totally understand what you mean, do you want protection stones to be pushed by pistons?

**Comment by espidev** [comment]
are you still having this issue?

**Comment by espidev** [comment]
no reply

**Comment by jonander2233** [comment]
Sry, if you put more than 1 protection block it bugs pistons

**Comment by espidev** [comment]
I'm unable to reproduce this issue, please explain further
