### ISSUE TITLE
Protection heads dropping normal heads and not working correctly

### ISSUE THREAD

**Issue by Roccia123** [espidev/ProtectionStones#385]
title.
This doesn't always happen sometimes it works correctly but when i break it and place it again it doesn't work.

**Comment by espidev** [comment]
strange, which version are you using

**Comment by Roccia123** [comment]
i'm using 2.10.3
i also tried turning off restrict_obtaining but it still doesn't work

**Comment by espidev** [comment]
Are you using an online server

**Comment by Roccia123** [comment]
yes i'm using aternos

**Comment by espidev** [comment]
Like I meant if the server checks for proper Minecraft accounts

**Comment by espidev** [comment]
Because that is a known issue if you have an offline server, which I do not support
