### ISSUE TITLE
Creepers don't explode in private.

### ISSUE THREAD

**Issue by arbuziksp** [espidev/ProtectionStones#388]
Creepers don't explode in private. Configured absolutely all flags that would creepers explode blocks in private, as a result, only dynamite explodes blocks, and creepers and whizers do not
    flags = [
        "pvp allow",
        "tnt allow",
        "greeting &lEntering &b&l%player%'s &f&lprotected area",
        "farewell &lLeaving &b&l%player%'s &f&lprotected area",
        "greeting-action &lEntering &b&l%player%'s &f&lprotected area",
        "farewell-action &lLeaving &b&l%player%'s &f&lprotected area",
        "creeper-explosion allow",
        "wither-damage allow",
        "ghast-fireball allow",
        "other-explosion allow",
    ]

    # List all the flags that can be set by region owners.
    # If you want to whitelist the groups that can be set as well, use -g (ex. "-g all,members pvp" restricts it to no group flag, and members group)
    # "-g all pvp" - Prevents players setting the group to nonmembers, and being invulnerable to attacks.
    allowed_flags = []

    # Which flags to hide from /ps info
    hidden_flags_from_info = [
        "ps-name",
        "ps-merged-regions",
        "ps-merged-regions-types",
        "ps-block-material",
        "ps-price",
        "ps-landlord",
        "ps-tenant",
        "ps-rent-period",
        "ps-rent-last-paid",
        "ps-for-sale",
        "ps-rent-settings",
        "ps-tax-payments-due",
        "ps-tax-last-payment-added",
        "ps-tax-autopayer"
    ]

**Comment by espidev** [comment]
do you have another plugin conflicting with this? i don't see anything wrong from what you've sent

**Comment by espidev** [comment]
Closed to inactivity
