### ISSUE TITLE
ps admin cleanup still bugged

### ISSUE THREAD

**Issue by Leonardo-Fiori** [espidev/ProtectionStones#39]
Just tested latest version of the plugin on my local LAN test server. I ran /ps admin cleanup remove 30 World, and It printed lots of "Failed to load player data for.." but sometimes it also printed "Removed region XX due to inactive members". My world is actually called World. With the capital W. Here is my latest log and the player data folder, just in case..

Tested on paper 107 (could not update to 1.14.4, there is still something in my plugins that causes map corruption on that version!).

https://drive.google.com/open?id=18p9c2GdixsezV92nVu-TkZ1RxQZuf7vv

https://drive.google.com/open?id=1C3lH4MzhT9UltxxzrpWnAFyirZR32lEv

**Comment by espidev** [comment]
The "failed to load player data for..." means the player's data is corrupted. You need to remove the player's data.

Luckily it seems you only have one player that is corrupted.

**Comment by espidev** [comment]
This message is actually from paper, not from the plugin

**Comment by Leonardo-Fiori** [comment]
> The "failed to load player data for..." means the player's data is corrupted. You need to remove the player's data.
> 
> Luckily it seems you only have one player that is corrupted.

Deleted the player data file, now i'm trying again.

Ok it worked perfectly! I tried also ps admin recreate and it worked too! Great job!

What about that offset that i suggested implementing? This is kinda offtopic here tho

**Comment by espidev** [comment]
Awesome, the other features are still in the queue, but I'm taking it a bit slower cause I have some other projects that I need to tend to
