### ISSUE TITLE
Problem, question.

### ISSUE THREAD

**Issue by Chilavekchilavek** [espidev/ProtectionStones#391]
how to make it so that when the tnt / creeper private block explodes, etc., the rg disappears? at the moment, my block drops out, and the rg remains... ( I set the values prevent_explode = false, destroy_region_when_explode = true in blocks.yml )

как сделать так, чтобы при взрыве блока привата тнт /крипером и т.п. рг исчезал? на данный момент у меня блок выпадает, а рг остается... ( я поставил значения prevent_explode = false , destroy_region_when_explode = true в blocks.yml )

**Comment by espidev** [comment]
This should work, do you have the latest version of paper and the plugin?

**Comment by espidev** [comment]
Closed to inactivity
