### ISSUE TITLE
PS crafting recipe does nothing

### ISSUE THREAD

**Issue by nnnarvaez** [espidev/ProtectionStones#398]
As the name says, the crafting recipe does not produce a PS

**Comment by espidev** [comment]
did you set `allow_craft_with_custom_recipe = true`

**Comment by nnnarvaez** [comment]
Yes i had, after much struggle i found i needed to add true  the use in crafting in the ingredient stone config file in the behavior part: 

```[behaviour]
	allow_use_in_crafting = false ```
