### ISSUE TITLE
Placeholders?

### ISSUE THREAD

**Issue by BloodshotPico** [espidev/ProtectionStones#41]
Was wondering about placeholders if they're a thing or not and if they're not would be interesting to see what placeholders could be put in place. For example:

Players Regions Count
Players Regions Broken
Protection Blocks Crafted
Protection Blocks given via /ps get

This is all I can think of as of now but I think this would be a cool feature to add if not in already.

**Comment by espidev** [comment]
you mean with placeholder API? I didn't know there was a demand for that...

**Comment by BloodshotPico** [comment]
Yeah sorry, And honestly placeholders are great I just love the information you can give players. :p

**Comment by espidev** [comment]
Being worked on now

**Comment by espidev** [comment]
Okay, I'm not sure if there is any purpose in these tags, which tags would you actually want?

**Comment by matahombres** [comment]
Examples:
%ProtectionStone_count% -> Count created protection stone
%ProtectionStone_defined-flag_<name>% -> Get true or false if protectionstone defined
%ProtectionStone_get-flag_<name>% -> Get value flag (Example -> gretting or farewell)
%ProtectionStone_allow_ps% -> List separate ',' with names if you can /ps get
%ProtectionStone_owner_<region>% ->Get owner
%ProtectionStone_members_<region>% -> Get members list
%ProtectionStone_name_<region>% -> Get name region
%ProtectionStone_block-status% -> Return true if block is hide / return false if block is unhide
%ProtectionStone_parents_<region>% -> Return list parents region

**Comment by espidev** [comment]
Finally assigned to 2.7.0

I've been very busy with school lately, so I will not be able to release this version this month most likely.

**Comment by leasoncre** [comment]
blocks.toml PAPI values ideas:

1. def want/need:
`%protectionstones-<alias>-blockdata-price%` #great for menu-creation (no need to reconfigure CommandPannels if price changes) - primary 'need' for this post :)

2. great to have:
`%protectionstones-<alias>-blockdata-displayname%` #reproduce item name EZ
`%protectionstones-<alias>-blockdata-lore%` #reproduce lore in command panels EZ, [multiline]
`%protectionstones-<alias>-economy-taxamount%` #[monthly] cost/rent
`%protectionstones-<alias>-economy-taxperiod%` #converted into years,months,days,hours,min,seconds? [ex: `1y2m3d4h5m55s`]
`%protectionstones-<alias>-economy-taxpaymenttime%` #converted time, "Grace period"

3. extras:
others nice to have, but i can't think of a need for at the moment
`%protectionstones-<alias>-worldlisttype%` #is it a blacklist or whitelist?
`%protectionstones-<alias>-worlds%` #blacklist/whitelist list (CSV) [not multiline
`%protectionstones-<alias>-region-xradius%`
`%protectionstones-<alias>-region-yradius%`
`%protectionstones-<alias>-region-zradius%`

**Comment by leasoncre** [comment]
> Examples:
> %ProtectionStone_count% -> Count created protection stone
> %ProtectionStone_defined-flag_% -> Get true or false if protectionstone defined
> %ProtectionStone_get-flag_% -> Get value flag (Example -> gretting or farewell)
> %ProtectionStone_allow_ps% -> List separate ',' with names if you can /ps get
> %ProtectionStone_owner_% ->Get owner
> %ProtectionStone_members_% -> Get members list
> %ProtectionStone_name_% -> Get name region
> %ProtectionStone_block-status% -> Return true if block is hide / return false if block is unhide
> %ProtectionStone_parents_% -> Return list parents region

does world-guard already have some of these? o.O 
found this with a quick google search ... https://api.extendedclip.com/expansions/worldguard/

**Comment by espidev** [comment]
I'll just add every single config option as a placeholder

**Comment by espidev** [comment]
Wiki page will be here with documentation: https://github.com/espidev/ProtectionStones/wiki/Placeholders
