### ISSUE TITLE
ProtcetionStones plugin does not work for version 1.16.5

### ISSUE THREAD

**Issue by KirillMrMeff** [espidev/ProtectionStones#410]
[latest.txt](https://github.com/espidev/ProtectionStones/files/15138582/latest.txt)
Hello! The ProtcetionStones plugin for version 1.16.5 does not work for me. I downloaded all the necessary plugins for this plugin. I have attached the server log. Help me please. I hope for an answer!

**Comment by espidev** [comment]
There appears to be some problem with your configs, try putting it in https://www.toml-lint.com/

**Comment by espidev** [comment]
Closing to inactivity
