### ISSUE TITLE
Griefing from outside the protection

### ISSUE THREAD

**Issue by qarbon1** [espidev/ProtectionStones#413]
Some players have discovered a new way of using lava and water from a high height and it can easily go into people's protections... is it possible to do something about it?

**Comment by Nadwey** [comment]
Use can enable `high-frequency-flags` and `protect-against-liquid-flow` in the WorldEdit configuration.

https://worldguard.enginehub.org/en/latest/config/#regions

**Comment by espidev** [comment]
Yes, please see the "other recommendations" section on the spigot page, it details what Nadwey shows above ^
