### ISSUE TITLE
Enchantment glint on block not working in 1.20.5+

### ISSUE THREAD

**Issue by EditChris** [espidev/ProtectionStones#415]
I'm trying this plugin in my Paper 1.20.6 server and when you break the block and get it back into your inventory, the block doesn't get the glint that has enabled in its config.

Should also be checked in 1.21, having enchantments now be data-driven could've broken this even further.

**Comment by espidev** [comment]
Which block are you using?

**Comment by EditChris** [comment]
It happens with the default block that comes with the plugin.

**Comment by espidev** [comment]
Fixed in v2.10.5
