### ISSUE TITLE
Players can Sell / Buy / Rent Regions

### ISSUE THREAD

**Issue by Leonardo-Fiori** [espidev/ProtectionStones#42]
Add the ability to sell or rent regions! Or ability to specify taxes! Similar to how towny works. This would be awesome.. maybe with the ability to use external economy systems or choose to just use a simple one integrated in the plugin, based on a specific item that should be placed inside a chest..

This would open up a lot of possibilities.

/ps setforrent price days
/ps removefromrent
/ps rent
/ps unrent

**Comment by espidev** [comment]
This might be suited for an addon plugin (ex. ProtectionStones-Towny?)

**Comment by Leonardo-Fiori** [comment]
> This might be suited for an addon plugin (ex. ProtectionStones-Towny?)

Yup. Absolutely. And it would be cool if it could support not just protection stones but world guard regions in general. If that's possible. Any ETA?

**Comment by Leonardo-Fiori** [comment]
@espidev Meanwhile i think i will have a workaround for this with Advanced Region Market.. i will define regions by my own.

Another (maybe easier to implement) addition that would be cool to have in protection stones is a daily/weekly/monthly cost for a specific protection stone.

**Comment by espidev** [comment]
I'll probably integrate basic economy function into PS

**Comment by espidev** [comment]
I've been putting this off for a while now, will still need to think of what is needed for this

**Comment by Leonardo-Fiori** [comment]
Ok thank you, I will patiently wait 😉

**Comment by espidev** [comment]
@Leonardo-Fiori How has Advanced Region Market been for you? Are there any features specifically from that plugin you would recommend to add, or anything missing?

Economy features are being fasttracked to 2.6.0

**Comment by Leonardo-Fiori** [comment]
@espidev that plugin is even too much for me.. it has groups and groups of flags.. a lot of features. PS needs to be simpler, just a simple rent buy and sell functionality. That uses the region's flags instead of using groups to be configured In the yml files. So, arm is pretty much too overwhelming but I still use it :)

**Comment by espidev** [comment]
What would happen if players don't have enough money to keep renting? Automatic eviction?

**Comment by Leonardo-Fiori** [comment]
Yup, they would simply be removed from owners. That's all.

_______

Another feature request:

Instead, another cool feature would be that regions that get their owner removed due to not logging in since too much time (with the command /ps admin cleanup disown) would be put in an automatic auction when players enter the them and try to buy them.

(Notice: this won't happen with /ps admin cleanup remove! That would spawn the sign, like requested on the other post)

This second feature would be toggleable. If someone do not want it to happen automatically there should be a command executable by players and by admins to set a region in an auction and to bid on it.

The problem is.. Can you differentiate regions that have no owners because the owner did not pay the renting from regions that lost owner due to ps admin cleanup (and so put them on auction)? This would be really cool to have, Like storage wars, the TV show.

**Comment by espidev** [comment]
The auction feature seems cool, but would not exactly be easy to do... I might consider it for future versions

**Comment by espidev** [comment]
Added to 2.6.0
