### ISSUE TITLE
Adiacent Protection Stones restriction

### ISSUE THREAD

**Issue by Leonardo-Fiori** [espidev/ProtectionStones#43]
Add the ability to allow the placement of a PS only if inside or adiacent to another PS of the same owner, similar to how factions works.. with a limit of X non-adiancent PS that are placeable.. over that limit, you can only place adiacent protection stones. Useful to avoid uneven spreading of regions.

This would help to keep the server very clean.

must-be-adiacent: true/false
max-non-adiacent-protection-stones: 10-20

**Comment by espidev** [comment]
Added in 2.3.0, performance improvements probably needed
