### ISSUE TITLE
PS get gui

### ISSUE THREAD

**Issue by HgeX** [espidev/ProtectionStones#45]
The idea is, when you type `/ps get`, it'd display me an inventory gui with the available protection stones, so I only have to click one of the displayed items, the inventory would just close, and I'd get the block. Another option is to show the names of the protection stones in the chat but make it clickable to give the item to the player who clicked. 

Imho this update would make getting protection stones more fancy and clear for players.

**Comment by espidev** [comment]
Added for 2.3.0

**Comment by HgeX** [comment]
You're awesome!
