### ISSUE TITLE
Don't deny placing protection stones in blacklisted worlds

### ISSUE THREAD

**Issue by HgeX** [espidev/ProtectionStones#46]
The title pretty much explains my idea. As of right now when I place a protection block in a blacklisted world, the plugin removes it and tells me, that I cannot create any zones in that world. However, I see a lot of my players struggling to figure out what to do (even though the displayed message tells them to type `/ps toggle`). So maybe it'd be better for everyone to just have ps toggle turned off in these worlds by default.

**Comment by espidev** [comment]
Probably going to implement as config option

**Comment by HgeX** [comment]
Thank you! <3

**Comment by espidev** [comment]
Implemented in 2.3.0
