### ISSUE TITLE
Full PlaceholdersAPI support and 

### ISSUE THREAD

**Issue by Dancbeunny98** [espidev/ProtectionStones#48]
It would be nice to make full support for this plugin "".

* This would help to display inscriptions on the exit and entry into the player’s region. Derivation of the number of regions and more.

**Comment by Leonardo-Fiori** [comment]
Yep absolutely helpful!

**Comment by espidev** [comment]
Being worked on now

**Comment by espidev** [comment]
Added to 2.5.0
