### ISSUE TITLE
flag groups

### ISSUE THREAD

**Issue by ZombieToad** [espidev/ProtectionStones#5]
when i set default flag use deny it denied the owner of the pstone and if you set it to allow everyone can use them. so i googled how to allow worldguard use flags for members and it said "/region flag spawn -g nonmembers use deny" and i tried "/ps flag -g nonmembers use deny" but it doesnt work

**Comment by espidev** [comment]
Have you confirmed /region flag works? I'll check the functionality of -g

**Comment by espidev** [comment]
The functionality does work, please reopen if you have issues
