### ISSUE TITLE
PS FLAG'S GUI

### ISSUE THREAD

**Issue by JhordanPG** [espidev/ProtectionStones#51]
Could you add a GUI for the flag's and add all the flag's available on the server? Open close doors, disable lava movement, entry and exit of people, use of enderpearl's, among other things, it would be super great, in advance thank you very much.

**Comment by JhordanPG** [comment]
![image](https://user-images.githubusercontent.com/42554918/62679067-ea527f80-b978-11e9-9ee3-d849dc9c2a8f.png)

Example image

**Comment by espidev** [comment]
It'll be a text based GUI for now since the inventory based GUIs are planned for an add-on plugin

**Comment by espidev** [comment]
Added for 2.3.0
