### ISSUE TITLE
Suggestion Command like /ps center

### ISSUE THREAD

**Issue by Faunablitz** [espidev/ProtectionStones#54]
Which shows you the center of the actual region and the center of future neighbor regions of the same type.

**Comment by espidev** [comment]
Hmm you mean visually?

**Comment by Faunablitz** [comment]
Yes, just like /ps view

**Comment by espidev** [comment]
Hmm integrating it into /ps view would be good

**Comment by espidev** [comment]
Added into 2.4.0
