### ISSUE TITLE
Rename regions renaming the Protection Stone in an Anvil.

### ISSUE THREAD

**Issue by Leonardo-Fiori** [espidev/ProtectionStones#55]
As the title says, allow users to rename the claims renaming the protection stone in an anvil, before placing it. It could be useful for entry ang farewell flags, as well for server using dynmap world guard.

This is a secondary feature, tho. Not as important as others.

**Comment by Leonardo-Fiori** [comment]
@espidev is shouldn't be very difficult, maybe you just need to listen when a block get renamed on an anvil, and if the block is a configured protection stone, instead of changing the name, set a special NBT tag for it containing the new region name. Something like this i guess? But i am not the programmer, so, it's up to you

**Comment by espidev** [comment]
The problem is PS is built off of the coordinates from the ids unfortunately, so renaming regions by names would need a rewrite of most of code...

**Comment by Leonardo-Fiori** [comment]
Uh.. sad story. Scrap this idea so.
