### ISSUE TITLE
Support custom player heads as Protection Stones!

### ISSUE THREAD

**Issue by Leonardo-Fiori** [espidev/ProtectionStones#56]
This would be a really cool one.

Add support for using player heads with a specific skull owner tag as protection stones.

Right now PLAYER_HEAD is supported, but there is no way to specify the skin of the skull.

This should be supported by shop plugins such as shopkeepers because you don't need any additional special tag to add to the item..

... and, to replace old protection stones with the new ones, a command like /ps admin convert OldStone NewStone that replaces all the existing claim blocks with the new ones. But this is getting pretty hard to do. Only if it is possible to do in an easy way. The main concern here is player head support.

**Comment by Leonardo-Fiori** [comment]
@espidev any idea if this could be easy to implement?

**Comment by espidev** [comment]
Currently preoccupied with the unmerge algorithm but I don't suspect this will be hard.

**Comment by Leonardo-Fiori** [comment]
@espidev is this finally going to be a thing in 2.5.0? What about for the command to replace old PS with the new player heads? :)

**Comment by espidev** [comment]
The heads part yes, the command I haven't decided yet...

**Comment by Leonardo-Fiori** [comment]
Ugh, I would have to make another conversion system.. like a shop at the spawn where players have to go and sell old for new PS. Pretty hard and time consuming. 

Isn't there a function to easily set a block to another block? Loop all the protection stones and use IDs to get coords as usual.. but I am just thinking, you are the dev 💪

**Comment by espidev** [comment]
@Leonardo-Fiori I'll see what I can do

**Comment by espidev** [comment]
Head part is roughly done, working on command

**Comment by espidev** [comment]
Command is done, ready for 2.5.0

**Comment by Leonardo-Fiori** [comment]
@EspiDev testing latest version right now... custom head support has a great issue, it does not support UUIDs.. the vast majority of custom heads use UUIDs, i don't know how to use them.

Then i tested it with some real nicknames. Notch did not work, mine, NemesiS_ITA, worked. MHF_ArrowUp did not work for example. For not working i mean that when i place it down nothing happens..

**Comment by Leonardo-Fiori** [comment]
For example, look here: https://minecraft-heads.com

**Comment by espidev** [comment]
Adding UUID support for 2.6.0

**Comment by espidev** [comment]
Strange though, since I'm able to get Notch and MHF_ArrowUp using player names fine...

**Comment by Leonardo-Fiori** [comment]
@espidev sorry recently i have really no free time.

I tested again, today on my main server.

I used PLAYER_HEAD:annayirb (that is a small redstone block replica)

When i place it down or break it, nothing happens.

But when i do /ps give it gives me the head with custom lore and title.. no errors on /ps reload. it see the new PS fine.

(Renamed to .txt to upload here)
[small.txt](https://github.com/espidev/ProtectionStones/files/3721764/small.txt)

Running latest version of PS that i found on Spigot..

Paper 213

openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu219.04)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu219.04, mixed mode, sharing)

**Comment by Leonardo-Fiori** [comment]
Still testing, it is not related to the head's name... and it does not happen every time. It happens with and without ALL the plugins. Except ps and WG WE of course.. try placing a PS in creative, then breaking it, then placing again, then logout, login, restart holding hands in hotbar.. try some stuff, sometimes happens that thing that i wrote above. But if i do /ps give again the new ps i get works, until it stops working again.

**Comment by espidev** [comment]
Hmm, I'll do further testing

**Comment by espidev** [comment]
Good news, I've been able to hack it so that /data works across worlds (using fake entities and weird stuff), meaning that you won't notice the difference between base64 heads and regular heads!

There will be a slight performance hit though with /ps admin changeblock, but hopefully it won't be too noticeable

**Comment by Leonardo-Fiori** [comment]
> Good news, I've been able to hack it so that /data works across worlds (using fake entities and weird stuff), meaning that you won't notice the difference between base64 heads and regular heads!
> 
> There will be a slight performance hit though with /ps admin changeblock, but hopefully it won't be too noticeable

Cool stuff! Maybe just keep both methods, when managing heads in the overworld just do a simple data set. When in other words do the stuff with entities. For example in my case I don't need PS in other words, so a nice and simple /data is fine 😃

**Comment by espidev** [comment]
tested in 2.6.0
