### ISSUE TITLE
Show greeting and farewell messages in the action bar!

### ISSUE THREAD

**Issue by Leonardo-Fiori** [espidev/ProtectionStones#57]
Show greeting and farewell messages in the action bar instead of the old regular chat. This would override worldguard flags, i guess.. maybe a farewell/greeting system built in just protection stones.

Bear in mind that this is a secondary/tertiary feature request..

**Comment by espidev** [comment]
I wonder if I could just submit a pull request to the WorldGuard Extra Flags plugin

**Comment by espidev** [comment]
You can track this here: https://github.com/isokissa3/WorldGuardExtraFlagsPlugin/issues/87

**Comment by espidev** [comment]
Finished, ready for 2.5.0
