### ISSUE TITLE
Show claim borders using particles instead of blocks

### ISSUE THREAD

**Issue by Leonardo-Fiori** [espidev/ProtectionStones#58]
Show claim borders using particles instead of blocks, like how the old famous Residence plugin works.. take a look here at this residence tutorial: https://youtu.be/Qx37Jkj0-50?t=273

Green and red particles appear, showing the residence's borders.

Could you implement something like that in protection stones? Maybe using some external World Edit selection visualizer plugin. Like the one made by the same authors of residence.

However this is a secondary feature request, i don't want you to be slowed down by this. Work on more important things first.

**Comment by espidev** [comment]
Possible with ProtocolLib...

**Comment by Leonardo-Fiori** [comment]
Take a look at this.. I don't know if it has an API tho.. http://www.zrips.net/svis/

It's really efficient with FPS and TPS

**Comment by espidev** [comment]
This should be coming up in 2.4.0

**Comment by espidev** [comment]
Ended up implementing it from scratch
