### ISSUE TITLE
New feature - Unclaim Protected Area on death

### ISSUE THREAD

**Issue by TheCrazyBoi** [espidev/ProtectionStones#59]
I have a new feature

Can you make it possible to unclaim protected areas for players that die? In my case, I am setting up a hardcore server and I want the feature that if a player dies, he will lose all his protected areas. Atleast make this a config feature so you can enable/disable it.

Regards Henrik.

**Comment by espidev** [comment]
/ps region disown [playername]
You'll have to run that command on death (possibly with another plugin).

Adding it as a config option might be a bit too specific of a feature...
