### ISSUE TITLE
ps view suggestion

### ISSUE THREAD

**Issue by HgeX** [espidev/ProtectionStones#6]
The ps view command is really handy if I want to visalize my zones actual size, however there's only one problem. I can spam it (I know, it's really dumb to do such a thing, but my players do it anyway), and then I'll lag and the server as well. In my opinion a cooldown would be nice. I mean, when I type /ps view I have to wait for 20-30 seconds before using this command again.

**Comment by espidev** [comment]
That's a good idea, I'll work on it for the next patch release.

**Comment by HgeX** [comment]
Thank you so much! :D

**Comment by espidev** [comment]
Added to latest version.
