### ISSUE TITLE
Support FAWE

### ISSUE THREAD

**Issue by Leonardo-Fiori** [espidev/ProtectionStones#61]
FAWE is a cool version of world edit. It allows you to work in a faster way on much much more blocks. However, when i have tried to use FAWE, Protection Stones did not work correctly because it could not find World Edit. It is probably incompatible.

Take this in consideration in the future, if you want Protection Stones to become a top claiming plugin.

**Comment by espidev** [comment]
FAWE is known to cause world corruption issues and is not exactly safe. The problem is that it isn't actually worldedit anymore, meaning that I'd have to recode a lot of stuff. I'd recommend this: https://www.spigotmc.org/resources/asyncworldedit.327/

**Comment by Leonardo-Fiori** [comment]
> FAWE is known to cause world corruption issues and is not exactly safe. The problem is that it isn't actually worldedit anymore, meaning that I'd have to recode a lot of stuff. I'd recommend this: https://www.spigotmc.org/resources/asyncworldedit.327/

Uh ok, if it's a lot of recoding, just don't even think about it.

So you are saying that that plugin actually makes world edit async without literally transforming it in another plugin? And it should be compatible with PS?

**Comment by espidev** [comment]
> > FAWE is known to cause world corruption issues and is not exactly safe. The problem is that it isn't actually worldedit anymore, meaning that I'd have to recode a lot of stuff. I'd recommend this: https://www.spigotmc.org/resources/asyncworldedit.327/
> 
> Uh ok, if it's a lot of recoding, just don't even think about it.
> 
> So you are saying that that plugin actually makes world edit async without literally transforming it in another plugin? And it should be compatible with PS?

Yep!
