### ISSUE TITLE
Prevent from breaking/placing blocks in whitelisted world

### ISSUE THREAD

**Issue by Rodrigo178** [espidev/ProtectionStones#64]
A config section to make that if a world is in whitelist for a block, player can't break or place blocks in that world, only protection stones

**Comment by espidev** [comment]
So they can only place blocks in their protected area?

**Comment by Rodrigo178** [comment]
Yes, only break/place blocks in their protected area.

**Comment by espidev** [comment]
For now, you can set block-break to deny for the __global region in WorldGuard and set block-break to allow for members in ps regions

**Comment by Leonardo-Fiori** [comment]
There are two flags in Wg Advanced Flags that could do this for you:

allow-block-place (list of blocks)
allow-block-break (list of blocks)

https://www.spigotmc.org/resources/worldguard-extra-flags.4823/

**Comment by espidev** [comment]
This feature is not really necessary, since you can apply flags the global region in WorldGuard (__global__)
