### ISSUE TITLE
Region Merging system improvements

### ISSUE THREAD

**Issue by Leonardo-Fiori** [espidev/ProtectionStones#68]
As a reminder of what i suggested you in #44 

1. Improve /ps view **FPS drop** on large merged regions (Reduce density? Render only particles that are near the player?)

2. Option for preventing to merge multiple regions inside a "blob" that has **holes inside** it (in the config.yml, add prevent-merging-inner-holes, or something like that)

3. **Limit the number of regions that can be merged** in a single "blob" to prevent lag when unmerging, relative to the size (inside .toml file add an option to decide how many of this kind of region could be merged inside a "blob". max-merge-number: X)

4. (**Improve unmerging** algorithm performance? Threaded?)

5. **Automatic merging** option for each protection stone in the .toml file (mergeable: true, auto-merge: true)

6. **Minimum distance** from one region to another also for the owner of the regions, to make players spread regions in the map more evenly.

I am still testing the latest dev build, i will report you other suggestions here, and problems in #44

**Comment by espidev** [comment]
> As a reminder of what i suggested you in #44
> 
> 1. Improve /ps view **FPS drop** on large merged regions (Reduce density? Render only particles that are near the player?)

In progress, should be better for the actual release.

> 2. Option for preventing to merge multiple regions inside a "blob" that has **holes inside** it (in the config.yml, add prevent-merging-inner-holes, or something like that)

Probably will be added once I come back from my trip (v2.4.1)

> 3. **Limit the number of regions that can be merged** in a single "blob" to prevent lag when unmerging, relative to the size (inside .toml file add an option to decide how many of this kind of region could be merged inside a "blob". max-merge-number: X)

Same as above (v2.4.1)

> 4. (**Improve unmerging** algorithm performance? Threaded?)

It's okay right now, but I'll continue investigating improvements.

> 5. **Automatic merging** option for each protection stone in the .toml file (mergeable: true, auto-merge: true)

v2.4.1

> 6. **Minimum distance** from one region to another also for the owner of the regions, to make players spread regions in the map more evenly.

v2.5.0+

**Comment by Leonardo-Fiori** [comment]
7. Implement a command that merges all the overlapping regions in the world if they have they respect a given criteria..

Example:

- an owner in common
- all owner in common
- must have no flags
- all flags in common

/ps admin forcemerge owner:all/one flags:none,all

(I closed the separate issue I made for this, let's post all the issues related to region merging here)

**Comment by espidev** [comment]
> 6. **Minimum distance** from one region to another also for the owner of the regions, to make players spread regions in the map more evenly.

Could you further explain minimum distance? Would this prevent merged regions from being formed?

**Comment by Leonardo-Fiori** [comment]
Simply an optional minimum distance from the region you are overlapping to.. with a custom message like "Hey you are placing this protection stone too near another one of yours"

Then if distance is respected and merging is enabled, merge it. If not skip merging..

**Comment by espidev** [comment]
> 2. Option for preventing to merge multiple regions inside a "blob" that has **holes inside** it (in the config.yml, add prevent-merging-inner-holes, or something like that)

Added for 2.5.0

**Comment by espidev** [comment]
/ps admin forcemerge caveats: doesn't know what to do when there is a region hole detected and allow_merging_holes is set to false. Currently it just doesn't merge the regions.

**Comment by espidev** [comment]
@Leonardo-Fiori I've decided to just implement the merging holes and /ps admin forcemerge from this issue for 2.5.0

I will be doing some testing, and hopefully releasing the weekend.

If you are able to test (much appreciated), here is the link to the latest dev build: https://ci.espi.dev/job/ProtectionStones/136/

I'd recommend testing on a development server for all of the new /ps admin commands (/ps admin forcemerge, /ps admin changeblock)

Thanks!

**Comment by espidev** [comment]
As for why I need to slow down the development, the project's structure has remained the same, despite the amount of code required for implementing these features: ![](https://i.imgur.com/mvrNDVJ.png)

Some parts of the code do look like a disaster right now, so implementing new features has become very slow and time consuming.

**Comment by Leonardo-Fiori** [comment]
I guess that's probably the right moment to take your time and start that very tedious thing called... Recode. 😭 As you wish.. if you prefer adding new feature it's ok! Take the time you need and thanks for all the work!

**Comment by espidev** [comment]
A few more questions:
> 5. **Automatic merging** option for each protection stone in the .toml file (mergeable: true, auto-merge: true)
Could you explain to the behaviour more? Is it that when you place a protection stone down, it'll merge automatically to regions nearby (if possible)?

> 6. **Minimum distance** from one region to another also for the owner of the regions, to make players spread regions in the map more evenly.
I'm still struggling to understand how this works, is it meant for being a minimum distance away from the closest region owned by the player, or something else.

**Comment by Leonardo-Fiori** [comment]
5. Yup! Just like that. Instead of needing to click merge, just merge it if possible.

6. Scrap this.. it would be too overwhelming for players

**Comment by espidev** [comment]
If there are two possible regions to merge to, I'll make it so that it asks again
