### ISSUE TITLE
Uuid cache idea

### ISSUE THREAD

**Issue by HgeX** [espidev/ProtectionStones#7]
I think that the uuid cache creation should be done asynchronously as now it freezes the server thread on startup for like 20 seconds (yeah, I have many registered players - many of them are bots lol). This update would speed up the starting process in my opinion.

**Comment by espidev** [comment]
Also a good idea. Until the UUID cache building is complete though, players will not be able to use /ps add 
 and remove for offline players.

**Comment by HgeX** [comment]
Yeah, that's true. But hopefully to the time when the server is fully loaded, the building process will be finished.

**Comment by espidev** [comment]
Added in the latest version. You have to enable this option manually since it isn't enabled by default (in config.toml)
