### ISSUE TITLE
Per Group Limit Protections

### ISSUE THREAD

**Issue by Yhenko** [espidev/ProtectionStones#70]
First of all, my english is bad, sorry :(.

Hi, I come here to suggest a Per Group Limit Protection System.

How it will be?

In config.yml should be a config like this (with protections that we previously created)

per_group_protection_system:
normalProtections: (or whatever we want):
 - Small
 - Medium
 - Big
 - Extremely Big

 VipsProtection: (or whatever we want)

 - SmallVipProtection
 - MediumVipProtection
 - BigVipProtection
 - ExtremelyVipProtection

And the permission should be like this:
protectionstones.limit.group.(groupname).(quantity) 
Normal Protections (protectionstones.limit.group.normalprotections.5)
Vip Protections (protectionstones.limit.group.VipsProtection.10)

Then with this permission and configuration we can place 5 normal protections: **ONE** Small Protection **AND FOUR** Medium Protection OR **Five** Big Protections OR **THREE** Small Protection **AND** Two Medium Protection...

So normal players can just place 5 normal protections AND vip players can set 5 normal protections and 10 vips.

Hopefull you can understand correctly, thanks and have a good day!

**Comment by espidev** [comment]
This sort of system seems kind of complicated, and I'm not sure if many people would use it...

Is there a specific reason you want this feature?

**Comment by espidev** [comment]
Inactive, not going to implement
