### ISSUE TITLE
ProtectionStones::Task: dev.espi.protectionstones.commands.ArgView taking too much time

### ISSUE THREAD

**Issue by Leonardo-Fiori** [espidev/ProtectionStones#72]
ProtectionStones::Task: dev.espi.protectionstones.commands.ArgView$$Lambda$5475/0x00000008417c7840 (Single)

Is taking 3 seconds in avg in my timings:

https://timings.aikar.co/?id=04fae333bdc04606bfc7d455666b6651#plugins

I am on the older PS plugin without region merging.. (ProtectionStones-2.3.1)

**Comment by espidev** [comment]
Yeah server performance is much worse with the old /ps view since it uses blocks. In order to get the performance benefits of /ps view particles you'll have to use the 2.4.x branch now

**Comment by espidev** [comment]
Sorry for slower responses, I'm in the middle of a forest lol
