### ISSUE TITLE
Deny-Message Flag

### ISSUE THREAD

**Issue by ivandelp** [espidev/ProtectionStones#74]
Set in config to disable deny-message in protections.

I add the flag deny-message -e but you can view "-e" message always in chat when you do something blocked. If you add manually deny-message -e, work, but if you add in config the flag, no.

**Comment by espidev** [comment]
Okay, I'll investigate a way to add this once I'm back

**Comment by espidev** [comment]
Sorry for the delays, I've had to bug test and fix quite a few issues in 2.5.0

I'm setting an ETA of roughly 2-3 weeks? I'm sort of busy with some other school related stuff too nowadays

**Comment by espidev** [comment]
Moved into 2.6.4

**Comment by espidev** [comment]
Added in 2.6.4
