### ISSUE TITLE
Fix /ps home in world blocked

### ISSUE THREAD

**Issue by JhordanPG** [espidev/ProtectionStones#76]
Can you arrange that you can use / ps home, from worlds where protections are disabled? Dude I'm in the nether or in the end, and he won't let me use / ps home

**Comment by espidev** [comment]
Currently /ps home only works per world unless you have a name set on the region because of the way WorldGuard works. I can investigate better world behaviour at some point

**Comment by espidev** [comment]
Naming the region should be enough, because id collisions would be messed up, and performance will suffer
