### ISSUE TITLE
More Protection Blocks

### ISSUE THREAD

**Issue by InfinityMage** [espidev/ProtectionStones#77]
In order to easily differentiate between Protection Stones and other blocks, I believe adding a feature to be able to place command blocks/structure blocks in survival would be useful, if possible. Another one would be to have the option to use a sign as the protection block, and when placed it would display information about the region, such as the radius and owner.

**Comment by Leonardo-Fiori** [comment]
I already suggested some time ago to add support for custom player heads.. that would be definitive.. there are many many custom heads that resemble blocks :) @espidev

**Comment by espidev** [comment]
@Leonardo-Fiori this is a bit different from custom player heads because command blocks are not placeable in survival

**Comment by InfinityMage** [comment]
Just wondering, how easy would it be to implement the custom signs? It would be displaying the region owner and radius/dimensions. @espidev

**Comment by espidev** [comment]
> Just wondering, how easy would it be to implement the custom signs? It would be displaying the region owner and radius/dimensions. @espidev

The custom signs in itself isn't hard, but it would be a lot of work (on the scale of the merging algorithm) for rewriting the item system since multiple protection regions would have to be possible with one type of item. Currently the entire plugin detects regions using the item material, so I would have to change it a lot.

I will focus on adding command block and structure blocks for now

**Comment by InfinityMage** [comment]
Alright, no problem. Thanks

**Comment by espidev** [comment]
Sorry for the delays, I've had to bug test and fix quite a few issues in 2.5.0

I'm setting an ETA of roughly 2-3 weeks? I'm sort of busy with some other school related stuff too nowadays

**Comment by espidev** [comment]
@InfinityMage are you satisfied with just using heads instead? The feature was added in 2.5.0, and works very well. There are possible issues with using command blocks, since they aren't placeable in survival, and I would have to reimplement block placing.

**Comment by InfinityMage** [comment]
@espidev I guess that would work, as the main reason is to differentiate from normal survival blocks. Just wondering however, what would reimplementing block placing include? Would it be tracking right clicks and finding air adjacent to the block face clicked, and then taking the item out of the players inventory and placing it? (I'm not trying to suggest that is easy to do fyi, I'm just interested because I've started trying to make my own plugins in java)

**Comment by espidev** [comment]
I guess there are multiple ways to do it (but not perfectly without a lot of work). You would listen to the player interact event and you could get the clicked block face, and place the block where the face. I actually did implement it for my server, but it's kind of buggy so I wouldn't recommend it too much: https://github.com/EstiNet/gFeatures/blob/master/src/main/java/net/estinet/gFeatures/Feature/SurvivalTwo/EventHub.java
