### ISSUE TITLE
Alternative to unclaiming regions

### ISSUE THREAD

**Issue by InfinityMage** [espidev/ProtectionStones#78]
For blocks that can't be broken/easily broken in survival, such as bedrock, being able to Shift+Right Click on a Protection Stone could be a nice option for unclaiming a region. I know that /ps unclaim is already a thing, but this would make it easier and would account for overlapping regions.

**Comment by espidev** [comment]
Sorry for the delays, I've had to bug test and fix quite a few issues in 2.5.0

I'm setting an ETA of roughly 2-3 weeks? I'm sort of busy with some other school related stuff too nowadays

**Comment by espidev** [comment]
Added in 2.6.0
