### ISSUE TITLE
New way to allow players to all regions

### ISSUE THREAD

**Issue by xFrann** [espidev/ProtectionStones#80]
Hey man, really like your plugin and it's nice to see those constant updates.
Could you tho add a command like /ps addall <playername> and of course /ps removeall to your plugin?
My players are facing constant issues with their protections 'cause they want to allow a player to all of their regions at once, without using merge.
Everytime there are 2 or more protection overlapping and it causes problems.
if you could add those 2 commands i'll be grateful.
Thanks

**Comment by espidev** [comment]
Hey, without merging, you can let regions share owners and members with /ps setparent

**Comment by espidev** [comment]
Basically use setparent to have all regions have their parent to be a main region: http://worldguard.enginehub.org/en/latest/regions/priorities/

**Comment by espidev** [comment]
no response
