### ISSUE TITLE
Chunk claiming mode AKA Snap PS to chunk's center

### ISSUE THREAD

**Issue by Leonardo-Fiori** [espidev/ProtectionStones#81]
This suggestion should not be a difficult one.

Add in each protection stones .toml file an option to enable chunk-claim-mode (Aka snap PS to chunk center).

What do it does?

- The X and Z claim size of the PS will be overridden with 16x16 (the exact number to claim a chunk). Y is left as choosen.

- When chunk-claim-mode is enabled player will be forced to place the protection stone in the cunk's central 2x2 blocks (chunk is 16x16 so there is not an exact central block, unfortunately), on a Y level that goes from bedrock to sky limit, player can choose at wich height.

- if the player does not place the PS in the 2x2 chunk's central blocks, a message will appear, and a column of particles will hilight the chunk central blocks. Example: "You need to place the protection stone in the chunk's center! Press F3+G to show chunks borders, or look at the particles."

- Implement the automatic-merge toggle that i suggested in the past, so you can enable it for regions set in chunk-claim-mode, so that they will automatically snap and merge together.

- Optional /ps autosnap command to automatically place the PS at the chunks center, for skilled players.

- When a player places a ps in chunk-claim-mode too near to another player's ps, just tell him that he can't. Don't use the default error message. It wouldn't be correct because he is forced to place it at the center, he cant move it just by some blocks.

Why?

Sometimes claiming with lots of different sized protection stones can get quite difficult, by this way the plugin will force players to claim in a grid-like system.

**Comment by espidev** [comment]
Okay this would be pretty complicated because the codebase right now for placing blocks has kind of become a disaster with all of the new features lol.

I will have to investigate this after the code is seriously refactored.

**Comment by Leonardo-Fiori** [comment]
Ok! I Will patiently wait :)

**Comment by Leonardo-Fiori** [comment]
Maybe I could implement this in an external plugin?
After all i just need to enable auto merge, make claim 17x17 and make the claim go from bedrock to sky.

Then write a plugin that forces players to place a block that is in a specific list of blocks in one of the 4 central blocks in the chunk.

This would go very well with a region taxing system.. ill open another issue for that, maybe you can do just that one. Let me know.

**Comment by espidev** [comment]
seems to have been referred to in #121
