### ISSUE TITLE
Menu Gui For Flags

### ISSUE THREAD

**Issue by plebexer** [espidev/ProtectionStones#84]
its simple, when a player uses /ps flags, it opens a menu with the flags and when they touch the items they enable or disable the flags, when adding a flag to the menu you should select wich item id has that flag, and also make the lores translatable so it is multilingual, i would like to see this feature.

**Comment by PlayingWithPi** [comment]
I like the method that WorldGuard has ... where you can add flags interactively within the chat.
It's more a pick&play method.

Would look into how they do what they do :)

**Comment by espidev** [comment]
@PlayingWithPi Just doing `/ps flag` is probably what you want

**Comment by Amelia-exe** [comment]
Feel free to close

**Comment by anjoismysign** [comment]
I recently made a UI layer for ProtectionStones (communicating with the API)
It offers UI for viewing protections inside the world you currently are at (feel free to suggest another way of displaying protections) and you are owner (allowing you to manage it) or a member (teleport you instantly).
https://www.spigotmc.org/resources/blobstones.109325/
Currently only offers PvP flag but feel free to suggest new flags ❤️

**Comment by espidev** [comment]
Cool!

**Comment by espidev** [comment]
Cool!
