### ISSUE TITLE
Flags are confusing the users

### ISSUE THREAD

**Issue by Synthhero** [espidev/ProtectionStones#87]
Flags are very confusing to the average 10 years old minecraft player. I would strongly recommend you to group the flags at the config file. So the server owner has to make a group of flags where there will be included the use of chests, buttons, doors, trappedoors, vechicles, boats beacons, furnance and tens of other usable blocks. With one command (/ps toggle <name of the group-flag> he can enable all of the grouped flags at the config file. 
For example 
![image](https://user-images.githubusercontent.com/19896745/65592464-460fb100-df97-11e9-89ce-9f3bf6a2bac3.png)
The prevent-use: is name of the group of the flags above. The user just has to typer /ps toggle prevent-use and the job is done. He doesn't have to enable one by one the use of the boats, the stonecutter, the lectern, the dispenser, the buttons etc. 
That feature would really make the things easier to the players and the admins can take the 100% of the control of what flag every precious stone has. The less commands the best.

**Comment by espidev** [comment]
The flag "use" covers all usage of blocks and the flag "chest-access" covers all chests. Flags are not actually done by the plugin, they are created by WorldGuard. You can just type /ps flag, and it gives a nice text GUI that you can click to change settings.
