### ISSUE TITLE
Prices and Refunds

### ISSUE THREAD

**Issue by Synthhero** [espidev/ProtectionStones#88]
A good way to give motives to the users to grind, kill mobs, use jobs plugins, trade & vote in order to earn ingame money. Is to ask for money every time a user is placing a protection stone. This way server is sinking some of the money and makes the game more challenging. I think t at you already have this but you need to add the **refund** possibility. Some owners including me dont want to fully refund the player after he breaks their protection block. 
This way they will think twice after they move and build to another place. This is very useful to servers with many players where none of us wants all of the map filled with abandoned buildings. This is also a good way to sink money and control the server economy, it is like taxes. My last argument is that sometimes griefers use protection stones to protect their ungly grief which is close others' buildings. If the griefer knows that he wont take all of his money back when he will break the protection stone that protects the grief he will think twice before he claim a destroyed area.

**Comment by espidev** [comment]
Added 2.6.0
