### ISSUE TITLE
I don't like /ps give 

### ISSUE THREAD

**Issue by Synthhero** [espidev/ProtectionStones#89]
Another thing that I really didn't like was /ps give. Using precious stones for years at my servers my players were mining all the time and trading ores in order to create the protection fields. Your plug-in gives them the stones without mining them that is a reason why the server has less challenge. 
Okay many of your plug-in users might like this function so I would recommend you to make it configurable like.
!If you want the players use mined stones a 
!protection stones set this to false
ps-give: true

**Comment by espidev** [comment]
Just don't give players the permission protectionsstones.give

**Comment by espidev** [comment]
It's not even meant for players, it's meant for admins to give ps to people, or if you were using a shop plugin

**Comment by Synthhero** [comment]
So as long as the players don't have the permission they place a mined ore and it becomes a protection field?

**Comment by espidev** [comment]
Oh, disable restrict-obtaining in the block config, so that it'll allow naturally obtained blocks to be used

**Comment by Synthhero** [comment]
Thanks :)

**Comment by espidev** [comment]
No, just be sure not to give protectionsstones.get either
