### ISSUE TITLE
Overlapping fields

### ISSUE THREAD

**Issue by Synthhero** [espidev/ProtectionStones#90]
When the player A has placed a protectionstone at its range the player B can not place a protectionstone. 
In some cases like tiny protections 5x5 that are made to protect rails their field shouldn't be an obstacle for somebody who wants to place city protection (100x100 for example) nearby.
So a nice idea was the ability of the A player's protection stone to accept the placement of another's player's stone no matter if they are overlapping, that doesn't go vice versa, for example the player A can not place the tiny protection inside the city protection of the player B (if the city protection is not configured to accept foreign protection stones inside their range). That means that each player can not break or place blocks or bypass flags at each other's field.

**Comment by Synthhero** [comment]
Is this that I'm talking about?
allow_overlap_unowned_regions = false

**Comment by espidev** [comment]
@Synthhero yes
